### ISSUE TITLE
/usr/local/lib/ruby/2.5.0/psych.rb:497:in `initialize': No such file or directory @ rb_sysopen - /home/sharad/MyopicVicar-master/config/errbit.yml (Errno::ENOENT)

### ISSUE THREAD

**Issue by Sharadd15** [FreeUKGen/MyopicVicar#1741] opened 2018-12-24 18:14 UTC
![screenshot from 2018-12-24 23-58-53](https://user-images.githubusercontent.com/44508838/50405101-f0279600-07d7-11e9-9fa0-31f76c2e118c.png)

**Comment by Captainkirkdawson** [comment] 2018-12-24 18:44
I do not know who sharadd15 is or what they are doing. The specific issue is caused by trying to install the code without setting up the necessary files being present. None of the essential configuration files are present in the repository only examples of what should be present. People who are collaborating with FreeUKGEN are provided with the guidance to get a working installation.

**Comment by Sharadd15** [comment] 2018-12-24 18:59
Greetings, I am Shard Shukla . I want to start contributing in the project.
Please guide me how should I start .

**Comment by Captainkirkdawson** [comment] 2018-12-25 17:33
Hello Shard; Could I suggest the best way for you to proceed is through our volunteering portal
https://www.freeukgenealogy.org.uk/about/volunteer/tech-volunteering-opportunities/
Given the season there may well be a delay in getting response as I know most people are currently with their families. @richpomfret you  may want to follow up directly

**Comment by Sharadd15** [comment] 2018-12-26 07:50
Greetings ,
I have submitted the google form two days back . I have gone through the
readme file so until my form gets accepted and I have a user id then I will
be able to install the application in my system . I understand it's
Christmas and new year after all. I want to start as soon as possible .
Looking forward to it.
Merry Christmas and a very happy new year

**Comment by Captainkirkdawson** [comment] 2018-12-28 15:34
I believe a member of the team should have been in touch with you so we will close this commentary

**Closed by Captainkirkdawson** 2018-12-28 15:34 UTC
Labels: invalid
