### ISSUE TITLE
Link database code to front-end design repositories

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#266] opened 2014-11-07 15:10 UTC
At present, @Captainkirkdawson and I are manually copying assets like logos, images, javascript snippets and stylesheets from the repository created by @joshangell et al. into the MyopicVicar codebase.  There are much less error-prone ways to do this, and Josh has been working towards a more modular, automated approach.

At the moment, Kirk and I still need to come up to speed on front-end work, but once we've got our heads around things, we should switch the framework over to a Bower-based solution.  

See chat log below
```
Josh:
Right - one of the things I wanted to check with you is the framework we've made for all future FreeUKGen projects
I'm pretty sure its not compulsory by any means but we thought it a good idea to consolidate all the resources that were the same across the two projects we know about - the one you're working on and the free uk gen website
To that end I created a Core repo that projects can inherit from using Bower.
bower.io
I have made an up-dated project for you guys using this new core framework and set up the project specific resources in there as well

Ben: 
Okay.
How does this sound for a strategy:
At the moment, Kirk and I are still getting our feet wet on front-end work.  Copying compiled assets into our project specific repo is about all we can handle.   However,
I'd like to create a tech debt story for us to switch over to multi-repo inheritance and really using Bower once we've got enough clue, front-end-wise.
Then we'd pick up the assets from the core repo, the project-specific repo
and we'd probably not point to local copies of assets within our source code, but rather use bower/grunt/etc to pull them in (presumably upon deployment)
Does that sound like an approach that might get us where we need to be?

Josh:
yes - that is exactly what I was shooting for

Ben:
OK.
It definitely won't be before November 20.
But possibly the following sprint.

Josh:
It could happen on deployment but it would probably be safer to manage the updates on a per project basis - it would just be quicker with bower etc
Anyway - I see your point and will just hold those for now

Ben:
So if I understand you,
Let's say an asset in the common repo changes (Free UK Genealogy changes their logo)
Then we'd run something in bower to pull that into our source, check it in, and deploy that?

Josh:
Yes - exactly

Ben:
So the copies would still be local, but the copying would be an output of a build process, rather than manual drag-and-drop by me or Kirk?

Josh:
Yes - I have set it up so bower only pulls in source files, then grunt (build tool) compiles those and any local ones into one big blob
Effectively.
The reason you wouldn't want to do it all on deploy is because you'd want to verify that the core changes hadn't messed with any of your local css / markup

Ben:
Ahh.  Right.

Josh:
So, in our scenario of building the new free uk gen site:
core contains css/images/svgs
our project pulls all that in, compiles it with our local stuff some of which overrides (hardly any actually) and a lot of which is extra js/css
that way we get the all the fonts, logos, colour variables etc without having multiple places where they are defined
Anyway - at present all this is sat on our github but it would be better from our perspective if it was sat on yours

Ben:
I'm very happy to add you to the github org, if you'd like to transfer the repos to FreeUKGen
I can do that right now, actually.

Josh:
Ah lovely thanks - then I'll write some readmes and you can peruse at your leisure
I have also been a bit over zealous and created a 'project template' repo - just to get you started with integrating the core into anything else
```

**Comment by dougkdev** [comment] 2015-08-28 02:03
After looking into the bower-based solution, we decided that it would only make sense to go that route if we were making frequent changes to the assets like designers do.   For our purposes, these are basically static assets that won't be changing (or at least will only change very infrequently).  Adding bower to our asset management would only add additional layers of complexity (and possible failure points) to our process without direct benefit.  For our purposes, the way Kirk and Ben have already been doing it (copying finished assets into the project) is the appropriate way to go.

**Comment by Captainkirkdawson** [comment] 2015-08-28 14:06
That is good news. 

But it does raise a question.

Do we need to continue with the inclusion of the Grunticon  js in the application layout

 <script type="text/javascript">
      /* grunticon Stylesheet Loader | https://github.com/filamentgroup/grunticon | (c) 2012 Scott Jehl, Filament Group, Inc. | MIT license. */
      window.grunticon = function(e) {
        if (e && 3 === e.length) {
          var t = window, n = !(!t.document.createElementNS || !t.document.createElementNS("http://www.w3.org/2000/svg", "svg").createSVGRect || !document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image", "1.1") || window.opera && -1 === navigator.userAgent.indexOf("Chrome")), o = function(o) {
            var r = t.document.createElement("link"), a = t.document.getElementsByTagName("script")[0];
            r.rel = "stylesheet", r.href = e[o && n ? 0 : o ? 1 : 2], a.parentNode.insertBefore(r, a)
          }, r = new t.Image;
          r.onerror = function() {
            o(!1)
          }, r.onload = function() {
            o(1 === r.width && 1 === r.height)
          }, r.src = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="
        }
      };
      grunticon(["<%= path_to_stylesheet('styles/css/icons.data.svg.css') %>", "<%= path_to_stylesheet('styles/css/icons.data.png.css') %>", "path_to_stylesheet('styles/css/icons.fallback.css') %>"]);
    </script>

**Comment by Captainkirkdawson** [comment] 2015-08-28 14:07
<script type="text/javascript">
      /* grunticon Stylesheet Loader | https://github.com/filamentgroup/grunticon | (c) 2012 Scott Jehl, Filament Group, Inc. | MIT license. */
      window.grunticon = function(e) {
        if (e && 3 === e.length) {
          var t = window, n = !(!t.document.createElementNS || !t.document.createElementNS("http://www.w3.org/2000/svg", "svg").createSVGRect || !document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image", "1.1") || window.opera && -1 === navigator.userAgent.indexOf("Chrome")), o = function(o) {
            var r = t.document.createElement("link"), a = t.document.getElementsByTagName("script")[0];
            r.rel = "stylesheet", r.href = e[o && n ? 0 : o ? 1 : 2], a.parentNode.insertBefore(r, a)
          }, r = new t.Image;
          r.onerror = function() {
            o(!1)
          }, r.onload = function() {
            o(1 === r.width && 1 === r.height)
          }, r.src = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="
        }
      };
      grunticon(["<%= path_to_stylesheet('styles/css/icons.data.svg.css') %>", "<%= path_to_stylesheet('styles/css/icons.data.png.css') %>", "path_to_stylesheet('styles/css/icons.fallback.css') %>"]);
    </script>

**Comment by dougkdev** [comment] 2015-08-28 17:14
I don't believe we need to.  I think we only need the finished asset files inside of the MyopicVicar project.  We should keep all the bower/grunt stuff in the Free-XYZ-Frontend projects so we can rebuild the assets if necessary due to any future changes, but I don't think there is any need to keep them within MyopicVicar since we are just copying the assets in instead of building the assets inside of the project.

**Comment by dougkdev** [comment] 2015-08-28 22:17
I verified that both sites run properly in development environment without the grunticon.js and also without the app/assets/stylesheets/styles/scss/* files, and removed those unnecessary files from MyopicVicar project.  Will wait to close this until we verify on the test server.

**Comment by Captainkirkdawson** [comment] 2015-08-28 23:48
Confirmed that FR2 is happy on test3 without the files that were deleted

I looked at removing the grunticon script that is in the application layout and determined that is needed to load the FR2 icon and the other icons in the banner. So appears our current styling requires it!!!
Tried just putting the <link rel="stylesheet" type="text/css" href="styles/css/icons.fallback.css"> in in place of the script to no avail.

**Closed** 2015-09-10 18:43 UTC
Labels: Actor: technician, enhancement
