### ISSUE TITLE
Add validation of Church Denomination

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#377] opened 2015-01-13 08:45 UTC
At present the Church Denomination is not field in FR1, so will need to be added as time goes on.  So now is a good time to standardise this.  It will be helpful to academic researchers to be able to select a specific denomination for analysis, but to do this the spelling will need to be standardised.  Now, or very soon, will be a good time to put this in.

**Comment by edickens** [comment] 2015-01-13 08:50
I don't know how this will be programmed, but it should be possible to easily add to this list.  For example we have received Burial records for Manchester's public cemetery, so this will require a denomination entry.

**Comment by Captainkirkdawson** [comment] 2015-01-14 00:50
This one is closed as it is essentially a duplicate of 376

**Closed** 2015-01-14 00:50 UTC
Labels: enhancement
