### ISSUE TITLE
Open data-Provide access on request to the full transcriptions on an approved basis

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#133] opened 2014-08-14 13:08 UTC

**Comment by PatReynolds** [comment] 2015-08-11 13:36
If Ben's first suggestion, I think this now overtaken by Open Data.

**Comment by benwbrum** [comment] 2017-03-21 13:52
Closing as duplicate of #1143

**Closed by benwbrum** 2017-03-21 13:52 UTC
Labels: epic, ready
