### ISSUE TITLE
Results for Bradford WRY when Bradford DEV searched.

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#2683] opened 2023-10-03 14:03 UTC
I have had this report from a researcher, I have checked using his search parameters and they do return Bradford WRY.

"I do not think there is anything wrong with this record (by itself) but it, and many other records for Bradford, West Yorkshire were returned when I made a query for members of the Arscott family in Bradford, DEVON. Possible database fault?"

![image](https://github.com/FreeUKGen/MyopicVicar/assets/10379655/c26b4116-1a59-4375-8659-a267b286a39a)

**Comment by Sherlock21** [comment] 2023-10-05 20:37
There IS  a place name in Devon called Bradford.
its location is 
50°50'27.2"N 4°14'43.6”W

and it has a church: All Saints.
there are a grand total of 5 records, which are all in the same family. - entered as an extract of a register for some reason known to the Coordinator of the time - ( John Pingham).

This place Bradford is near to a better known place of Holdsworthy.

-Eric Booker
Data Manager

On 3 Oct 2023, at 15:03, suffolkroots ***@***.***> wrote:


I have had this report from a researcher, I have checked using his search parameters and they do return Bradford WRY.

"I do not think there is anything wrong with this record (by itself) but it, and many other records for Bradford, West Yorkshire were returned when I made a query for members of the Arscott family in Bradford, DEVON. Possible database fault?"

 <https://user-images.githubusercontent.com/10379655/272287793-c26b4116-1a59-4375-8659-a267b286a39a.png>

**Comment by suffolkroots** [comment] 2023-10-06 05:42
The links to Bradford WRY and Bradford DEV are both correct.

Question is---why does a search on Bradford DEV return results for Bradford WRY?

**Comment by edickens** [comment] 2023-10-06 07:07
I think we have had this before.  The problem is that the Search does not use Couinty+Place in the search, just Place.  If someone knows of another example of duplicate Place names in differnet counties, where we have records, then could they try a search and see if the same result occurs.

**Comment by suffolkroots** [comment] 2023-10-06 08:27
That sounds strange, if the search is not on county then place, please may I suggest that it should be?

Otherwise what's the point of selecting county then place?

**Comment by Sherlock21** [comment] 2023-10-07 11:21
There must be many place names that occur in more than one County -though I cant just think of them off the cuff.

someone who has access to the code table should be ably to do this easily,
Eric B

On 6 Oct 2023, at 08:07, Eric Dickens ***@***.***> wrote:


I think we have had this before. The problem is that the Search does not use Couinty+Place in the search, just Place. If someone knows of another example of duplicate Place names in differnet counties, where we have records, then could they try a search and see if the same result occurs.

**Comment by Sherlock21** [comment] 2023-10-07 12:59
I have just done a simple little task based on the Place Names table that Kirk used in his code. Some of these places may not have churches or records, but ther will be many that do, and so the FreeReg code should allow for {Place name + County} always, surely

Abbey Green is in Shropshire and Staffs
Abbey Gate is in Devon & Kent
Abbeydale is in Gloucester & West Riding
Abberton is in Essex & Worcester
Abbotswood is in Hampshire & Surrey
Aber is in Caernarvon & Cardigan

Leeds is in West Riding and Kent

to name but a very small few.

SO I am surprised that we have got a situation where Place name is not linked to County when doing any search.

Eric B  

On 7 Oct 2023, at 12:21, Eric Booker ***@***.***> wrote:

There must be many place names that occur in more than one County -though I cant just think of them off the cuff.

someone who has access to the code table should be ably to do this easily,
Eric B

On 6 Oct 2023, at 08:07, Eric Dickens ***@***.***> wrote:


I think we have had this before. The problem is that the Search does not use Couinty+Place in the search, just Place. If someone knows of another example of duplicate Place names in differnet counties, where we have records, then could they try a search and see if the same result occurs.

**Comment by SteveBiggs** [comment] 2023-10-07 13:02
Despite what the Erics have said, this should NOT be happening and is a bug. If you search for Bradford DEV you should only get results from DEV. This needs to be addressed at the next scrum.

**Comment by Sherlock21** [comment] 2023-10-07 14:11
To make it clear, my view has been that what is currently happening is wrong.

I have just done a little check in for place names beginning ‘A’ there are 286 Place Names that are duplicates ie the name occurs in more that one County.

EricB 

On 7 Oct 2023, at 14:03, Stephen Biggs ***@***.***> wrote:


Despite what the Erics have said, this should NOT be happening and is a bug. If you search for Bradford DEV you should only get results from DEV. This needs to be addressed at the next scrum.

**Comment by DeniseColbert** [comment] 2023-11-22 15:24
@Vino-S to create a rake task to help estimate the number of records affected by this issue.

**Comment by DeniseColbert** [comment] 2024-01-17 15:39
Check that this fixes other places (e.g. Sutton) when done

**Comment by Vino-S** [comment] 2024-02-14 13:48
Ready for testing in test3

**Comment by suffolkroots** [comment] 2024-02-20 05:18
Test returns only results for correct county in both cases.

**Comment by DeniseColbert** [comment] 2024-04-10 14:22
@Sherlock21 could you use the Clean UCF list function in the Manage Counties action to test 

"Leeds is in West Riding and Kent"

If you use the button and the issue is fixed, this story can be closed.

**Comment by DeniseColbert** [comment] 2024-05-08 14:07
@Vino-S to ask Eric B to test offline

**Comment by DeniseColbert** [comment] 2024-07-03 13:35
Done, closing

**Closed by DeniseColbert** 2024-07-03 13:35 UTC
