### ISSUE TITLE
Review of results from Shaw Trust review

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#845] opened 2016-07-01 08:42 UTC

**Comment by PatReynolds** [comment] 2016-07-04 10:04
I have (temporarily) given this a 1.5 milestone as I think we have only a limited time for a re-submit (6 months). The work is likely to be suitable for the new html/css volunteers, so will not have a large impact on development schedules

**Comment by Captainkirkdawson** [comment] 2016-09-06 16:55
Duplicate of 903

**Closed** 2016-09-07 17:53 UTC
Labels: duplicate
