### ISSUE TITLE
Researcher data error reports distribution

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#459] opened 2015-04-16 16:35 UTC
When a researcher reports a data error, reports are generated but who to?

**Comment by edickens** [comment] 2015-04-16 16:39
The report just says "To:" and does not show who it is copied to.  This has caused confusion since all recipients have replied to the researcher.
The "To:" needs to be the CC and the "cc:" needs to be "reg-data@freereg.org.uk"
At present it goes to EricB because we have been searching for place name errors, but in FreeREG1 data errors go to the Alias list, so FreeREG2 should do the same now.
Thanks
E

**Comment by Captainkirkdawson** [comment] 2015-04-17 04:12
We do not use the Alias system which was designed for FreeBMD in the old
days over which we have no real control or influence as it operates in a
very different manner.

We use the role of people in FreeREG2 something over which you have real
time control

You can define more than one person for a role if you wish.

You can add more roles if you think that necessary.

As for the message they are common to a number of messages.

Guess we need to add a range of specialized messages at some point.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment] 2015-04-19 11:02
Diana (SOM) has requested that the Parish name goes in the message Subject.  This is to make it easier to pass on to the relevant transcriber.
Also, the version of the message sent to the CC seems to be different to that posted to the Waffle Board.  It would be helpful if all versions were the same and all addressees are cc: and then we all know who has copies.
For the time being, can a copy be sent to reg-data@freereg.org.uk so that Bob Wilkins gets a copy.  He is the data corrections coordinator.
E

**Comment by edickens** [comment] 2015-04-19 11:08
I think that there is another story about this, but I cannot find it. 
The links to the Record and Contact do not seem to work.

**Comment by Captainkirkdawson** [comment] 2015-04-19 14:43
You must be logged in for them to work since they are privileged

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment] 2015-04-19 14:45
Currently copies go to the CC and datamanager

Will add Bob Wilkins on my return

Do you want to add a data corrections coordinator role?

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment] 2015-04-19 14:57
Kirk,
Please make it the Corrections Manager and the email address (which I 
will enter when set up) is reg-corrections@freereg.org.uk
No need to add Bob, as this email address will get to him.
Thanks E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by edickens** [comment] 2015-04-19 15:01
When a recipient of a data error report selects a link to the record, can FR2 warn them if they are not logged in and invite them to log in.  Otherwise it is a double process of seeing the message, leaving the email editor, using  the web browser to log in, then returning to the message.

**Comment by Sherlock21** [comment] 2015-04-19 15:32
As I have reported before, I cannot navigate to anywhere on either the "record in question" nor on the "Access the Contact" button from a reg-web@freereg.org.uk message about data faults-And i am logged on to Github and the FR2.

**Comment by Captainkirkdawson** [comment] 2015-04-19 16:27
Have you tried going to the Contacts Action when you have logged in?

**Comment by Sherlock21** [comment] 2015-04-19 16:35
in the absence of any other clues, I had
a Github session open, showing this page on which I comment.
I had a FR2 search start page showing, and I was logged on to FR2 Members.

I have no where else to log on to.
Then on the email which  I received stating the problem, I clicked on the button at the bottom of that email labelled Access the contact.

**Comment by edickens** [comment] 2015-04-19 16:48
Got that now.  But CCs cannot log in so I will need to copy and paste 
for them for the time being.
Thanks E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment] 2015-04-19 17:00
EricD Agreed it is a pain at the moment but should not be for too long;
sorry I had to go on vacation again!
EricB You also have the ability to go to the Contacts Action and review
there.
Please forward me an email of a contact for me to have a look at.
K

**Comment by Captainkirkdawson** [comment] 2015-05-08 14:00
Duplicate of 468

**Closed** 2015-05-08 14:00 UTC
Labels: Actor: county coordinator, bug, duplicate
