### ISSUE TITLE
User Refinery entry destroyed on login while locked for maintenance

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#779] opened 2016-05-02 14:23 UTC
When the system is placed in maintenance mode any attempt to login that is rejected has the refinery user entry removed

**Comment by dougkdev** [comment] 2016-05-04 20:07
The user refinery entry also gets deleted in other cases, such as if the
user tries to log in while their account has been marked "inactive" or if
their role is "researcher" or "pending".
I believe I found the problem and am now looking into the solution.

Technical details for CaptainKirkdawson and benwbrum:
  I believe it is because in each of these cases, there is an explicit
current_refinery_user.delete in manage_resources_controller.rb, which
appears to be deleting the actual refinery entry instead of the session
variable (which I assume was the intent).  I assume current_refinery_user
is set by (or is a function in?) refinery itself as I did not find where it
is set in our code with recursive grep, so I am still looking into where it
is coming from.  If I just do a session.delete(:refinery) instead of
current_refinery_user.delete we get stuck in a redirect loop, so I'm still
looking at the proper way to clear the current refinery user without
deleting the database entry.

**Comment by Captainkirkdawson** [comment] 2016-05-04 20:14
Excellent diagnosis Doug. I cannot for the life of me remember why we were doing the delete.

There had to be a reason (I hope)

Do we even need it?

**Comment by benwbrum** [comment] 2016-05-04 20:14
current_user is a pretty standard Devise method, and Refinery uses Devise
under the hood for user account and login management.  See
https://docs.omniref.com/ruby/gems/refinerycms-core/3.0.0/symbols/Refinery::ApplicationController/current_refinery_user

I'd think we'd want to either look for a "log out" method we could call, or
*maybe* set current_refinery_user=nil

**Comment by dougkdev** [comment] 2016-05-04 20:17
Thanks both of you.  I tried setting to nil along with the session delete
and it was still a redirect loop.  I'll look for logout and also the logic
at the login page where it is redirecting to.

**Comment by benwbrum** [comment] 2016-05-04 20:18
It looks like devise has a sign_out controller method that takes a user
object.

I'd bet that doing
authorisation_manager.sign_out(current_refinery_user) will work, but we
probably will need to do some plumbing to get at authorisation_manager.

Ben

**Comment by Captainkirkdawson** [comment] 2016-05-04 20:19
I think Ben has hit the reason. Its because we return to the login in page on boot out so that we can display the reason for the boot out
If we boot out to the logout page we cannot give a message

**Comment by Captainkirkdawson** [comment] 2016-05-04 20:19
refinery gives it own logout message and ignores ours

**Comment by dougkdev** [comment] 2016-05-04 21:27
Thanks.

sign_out(current_refinery_user) works.

I pushed the fix to master.

**Comment by dougkdev** [comment] 2016-05-04 21:31
And since current_refinery_user appears to be a function instead of
variable, that makes me wonder if the assignment in
next_place_to_go_successful_create (userid_details_controller.rb) is doing
what was intended?

**Comment by Captainkirkdawson** [comment] 2016-05-04 21:48
Does it pass our message?

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by dougkdev** [comment] 2016-05-04 22:39
Yes

**Comment by Captainkirkdawson** [comment] 2016-05-04 22:41
Thanks Doug.

**Comment by edickens** [comment] 2016-05-05 06:48
If I remember correctly, the password is deleted when a "Password
    change request" was sent by the SC.  Similarly if someone selects "I
    forgot my password" and the server sends a reset request.  E
    
    On 04/05/2016 21:14, Kirk Dawson wrote:
    
    
      Excellent diagnosis Doug. I cannot for the life of me remember
        why we were doing the delete.
      There had to be a reason (I hope)
      Do we even need it?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment] 2016-05-05 14:24
The current password is not deleted until the user enters another password

**Closed** 2016-05-30 04:38 UTC
Labels: bug, Urgent
