### ISSUE TITLE
Homepage statistics

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#436] opened 2015-03-19 16:54 UTC
FR1 has some statistics on content and usage.  Will this be in FR2?

**Comment by edickens** [comment] 2015-03-19 17:00
I know that there is another story about detailed statistics for future work, but if 1.1 is to replace FR1, I think we may get questions as to why there are no homepage statistics.  There are details by place etc., but not a total.
Also, with daily updating from FR1, are the place statistics being updated?

**Comment by Captainkirkdawson** [comment] 2015-03-19 17:10
On Thu, Mar 19, 2015 at 11:00 AM, Eric Dickens <notifications@github.com>
wrote:

> I know that there is another story about detailed statistics for future
> work, but if 1.1 is to replace FR1, I think we may get questions as to why
> there are no homepage statistics. There are details by place etc., but not
> a total.
> Also, with daily updating from FR1, are the place statistics being updated?
>

Don't know what you mean?

**Comment by Captainkirkdawson** [comment] 2015-03-26 14:26
Duplicate of 274 and 399

**Closed** 2015-03-26 14:26 UTC
