### ISSUE TITLE
Emails: bouncing and deceased

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#744] opened 2016-02-25 08:52 UTC
From discussions it appears that there is only one email associatied with each transcriber which is changed to facilitate management - we need to preserve last-known real email, mark it as non-functioning if it does not work.  We also need to record transcribers as deceased.

**Comment by Captainkirkdawson** [comment] 2016-05-09 14:18
There is no need for coordinators to change email addresses of a transcriber except when asked to so do by the transcriber (Transcriber can do for themselves). In reality they should not be doing it to facilitate management. It is bad practice.
There are  a selection of reasons for making a transcriber inactive. Death is one of them.
Is there any further requirement?

**Comment by edickens** [comment] 2016-05-09 14:54
I have been changing email addresses because I have not - until now
    - had confidence in the Message System.  The reason is that when I
    send, or resend, a message, the default is "Active" = Unticked. 
    This I assume is to send to both Active and Inactive.  If ever a
    message goes to some Inactive we have big problems.  People have
    asked us to take them off our records and removed their files.  We
    have not done this, but just made them "Inactive".
    
    Perhaps we should have a procedure that if someone wants to be taken
    off AND THEY DO NOT HAVE A ANY FILES, then we do actually destroy
    their UserID.  This has the advantage that if they change their
    mind, they can re-register with the same UserID.  E
    
    On 09/05/2016 15:18, Kirk Dawson wrote:
    
    
      There is no need for coordinators to change email addresses of
        a transcriber except when asked to so do by the transcriber
        (Transcriber can do for themselves). In reality they should not
        be doing it to facilitate management. It is bad practice.
        There are a selection of reasons for making a transcriber
        inactive. Death is one of them.
        Is there any further requirement?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment] 2016-10-25 14:06
Duplicate of 989 and 990

**Closed** 2016-10-25 14:07 UTC
Labels: Communication, Urgent
