### ISSUE TITLE
Nuisance registrations

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1126] opened 2017-03-07 10:48 UTC

**Comment by edickens** [comment] 2017-03-07 10:54
Ken (WAR) has had three registrations started, one which looks like this (Ken is in Spain hence the Spanish in the titles):-

De: freereg-registration@freereg.org.uk <freereg-registration@freereg.org.uk>
Enviado: lunes, 6 de marzo de 2017 21:24
Para: Kenneth
Asunto: FreeReg userid creation
 

Dear Kenneth; (Coordinator for )

The person Jacobdrerm Jacobdrerm at mari7l@hotmail.com has registered with FreeREG using an userid of 6.45. A link has been sent to them to establish a password and confirm their email address. You should receive confirmation of that final step in the registration process as soon as they have set up their password.

The FreeREG Team

So far, and I doubt that they will, registration has not been completed.  But this will leave a half completed UserID on the Server.  The only way to get rid of it is for the SC to email me to "Destroy" it.  I think we need a better system for registrations that are not completed say within a week.  They ought to complete within a few minutes.  E

PS.  Ken's  syndicate name should show.

**Comment by Captainkirkdawson** [comment] 2017-03-07 17:06
Appears to be a duplicate of 932. Can we combine the 2

**Comment by edickens** [comment] 2017-03-07 17:25
Yes, combine.  But I think we should now add an automatic deletion of a UserID after a week if registration is not complete.  In this way we will not have to check and delete all these UserIDs.  They can start again if needed and the password reset will have expired.
Unfortunately all these are getting set up on the Image server and I will have to delete those.

**Comment by Captainkirkdawson** [comment] 2017-03-07 17:46
Put whatever you want from here into the other

**Closed by Captainkirkdawson** 2017-03-07 17:46 UTC
