### ISSUE TITLE
Error Message at /manage_counties/ at Manage Images selection

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1604] opened 2018-09-30 13:50 UTC
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5bb0661be93790d93714472f)

Economic 0, Urgency 6, Strategy 8, Cost ?7 (for investigation): P=23
needs #1619

**Comment by smrr723** [comment] 2018-09-30 13:56
Error message being shown at https://www.freereg.org.uk/manage_counties/selection?option=Manage%20Images when users navigate to Manage/County/Manage Images, although navigating via /Manage Image Server and /Manage Syndicate/Manage Images, both work.

As discussed earlier @SteveBiggs

**Comment by SteveBiggs** [comment] 2018-10-01 13:29
The last action carried out by Ali was to create a Parish Register for Barnoldswick Holy Trinity, then click Create Image server. This gave the red "Something is wrong ...." message and now that comes up on trying to select Manage Images under Manage County for WRY.

I looked on the image server and the register folder for Holy Trinity was created.

**Comment by smrr723** [comment] 2018-10-01 22:05
@SteveBiggs @bev-fc - status update: code fix pushed up to colobus only, but no luck - still getting the Errbit error.

@SteveBiggs - can you confirm the error began on the 29th (Saturday night)?  This is what it looks like from the emails.  The log files are massive so I just want to make sure I'm looking at the right day.

I'll resume looking into this tomorrow.

**Comment by SteveBiggs** [comment] 2018-10-02 08:47
Yes, Ali reported that it started on Saturday night. I'm wondering if it would help to delete the empty Barnoldswick Holy Trinity folder from the image server since that was the last action Ali made? @edickens could you delete it please?

**Comment by smrr723** [comment] 2018-10-02 08:55
Ok, thanks.  

Her previous action was going to be my next question, so yes, definitely give that a try, and failing that - check if there were any other folders she was uploading to around the same time, and do the same.

**Comment by SteveBiggs** [comment] 2018-10-02 09:19
Let's see if deleting Holy Trinity helps first. Prior to that Ali had been uploading lots of images to Barnoldswick St James PR, but that was before the error occurred.

**Comment by SteveBiggs** [comment] 2018-10-02 14:32
@edickens has deleted the Barnoldswick Holy Trinity folder from the image server, but it has not affected the problem. Do we have to look at deleting Barnoldswick St James PR and all the (hundreds of|) images Ali uploaded on Saturday? I have little confidence that will make a difference either, but maybe worth a try. Perhaps @edickens can re-upload them after the issue is resolved?

**Comment by Sherlock21** [comment] 2018-10-02 14:40
Just hold off a moment please.

Discuss with Ali Hill first, as there happens to be an issue with the Church names in Barnoldswick, which needs resolving at the sae time.

**Comment by edickens** [comment] 2018-10-02 14:52
We first need to find out why we cannot get into WRY Manage Images when we can for other counties.

**Comment by SteveBiggs** [comment] 2018-10-02 14:55
@edickens that is the whole purpose of this issue

**Comment by edickens** [comment] 2018-10-02 15:03
Kirk told me that deleting, or making an changes, via BitKinex will upset the links within the server, so must only be done with great care.
Let me know what you find with the Church names.

**Comment by SteveBiggs** [comment] 2018-10-02 15:20
Just checked with Ali -
- there is nothing wrong with Barnoldswick church names on the site. It is a separate off-site issue re which is parish church.

I agree we should not delete any more images/folders from the server. @smrr723 @bev-fc do you have any other ideas to try to fix this please?

**Comment by edickens** [comment] 2018-10-02 15:55
I can reinstate the Holy Trinity folder if necessary because there were no images.

**Comment by SteveBiggs** [comment] 2018-10-02 16:04
Not sure it will make any difference, but you can try it.

I tried deleting the Holy Trinity register as it has no batches under it, but that failed because it says there are dependent documents, so it still thinks there is a corresponding folder on the IS even though you deleted it.

**Comment by edickens** [comment] 2018-10-02 16:42
I think the dependent document is a Source, but there is no means to delete it.

**Comment by edickens** [comment] 2018-10-02 16:46
Barnoldswick Holy Trinity PR reinstated.

**Comment by smrr723** [comment] 2018-10-02 17:21
@bev-fc and I are discussing a solution to print out some log info first so we can try to identify the problem file, and we can take it from there.

**Comment by smrr723** [comment] 2018-10-02 19:27
@bev-fc - log output below..

```out: ========================== source.rb log start ===========================
App 48384 stdout: source_id=5a9ed149f493fdbfcb9c875f, register_id=564deb4bf493fd42d800088c, source_name=Image Server
App 48384 stdout: source_id=5a9ed14cf493fdbfcb9c886b, register_id=54104dceeca9eb7bd3000002, source_name=Image Server
App 48384 stdout: source_id=5a9ed16af493fdbfcb9c916d, register_id=5a2be11bf493fda956111476, source_name=Image Server
App 48384 stdout: source_id=5a9ed171f493fdbfcb9c91f1, register_id=564dede8f493fd42d80008c3, source_name=Image Server
App 48384 stdout: source_id=5a9ed173f493fdbfcb9c92d7, register_id=5409f75beca9eb7182952019, source_name=Image Server
App 48384 stdout: source_id=5a9ed177f493fdbfcb9c9439, register_id=564d9613f493fd42d80001fa, source_name=Image Server
App 48384 stdout: source_id=5a9ed179f493fdbfcb9c94f8, register_id=540a15fceca9ebd28e1b96c1, source_name=Image Server
App 48384 stdout: source_id=5a9ed17af493fdbfcb9c9559, register_id=54086224eca9eb02487a9f10, source_name=Image Server
App 48384 stdout: source_id=5a9ed17cf493fdbfcb9c9628, register_id=5584bd1bf493fd5e850277ee, source_name=Image Server
App 48384 stdout: source_id=5a9ed17ff493fdbfcb9c9722, register_id=54080f09eca9eb02488fd223, source_name=Image Server
App 48384 stdout: source_id=5a9ed180f493fdbfcb9c97be, register_id=54080f20eca9eb0248900fbb, source_name=Image Server
App 48384 stdout: source_id=5a9ed182f493fdbfcb9c9884, register_id=5409aec9eca9eb0d224ba02c, source_name=Image Server
App 48384 stdout: source_id=5a9ed183f493fdbfcb9c98fb, register_id=5409f4b5eca9eba206918392, source_name=Image Server
App 48384 stdout: source_id=5a9ed185f493fdbfcb9c99b0, register_id=5409efb3eca9eb71827a2d85, source_name=Image Server
App 48384 stdout: source_id=5a9ed19bf493fdbfcb9ca0be, register_id=594a458cf493fd48f51c7afb, source_name=Image Server
App 48384 stdout: source_id=5a9ed215f493fdbfcb9cc0bd, register_id=540800ceeca9eb02486c80a9, source_name=Image Server
App 48384 stdout: source_id=5a9ed21ef493fdbfcb9cc1f8, register_id=571deacef493fde8030002a0, source_name=Image Server
App 48384 stdout: source_id=5a9ed221f493fdbfcb9cc322, register_id=56faa51af493fd5786000a06, source_name=Image Server
App 48384 stdout: source_id=5a9ed226f493fdbfcb9cc4a9, register_id=5a9ed225f493fdbfcb9cc491, source_name=Image Server
App 48384 stdout: source_id=5a9ed228f493fdbfcb9cc595, register_id=5409f0a3eca9eb71827d5d17, source_name=Image Server
App 48384 stdout: source_id=5a9ed22cf493fdbfcb9cc703, register_id=56faab6ef493fd5786000a59, source_name=Image Server
App 48384 stdout: source_id=5a9ed230f493fdbfcb9cc8ad, register_id=55a1c057f493fd1db901aad3, source_name=Image Server
App 48384 stdout: source_id=5a9ed234f493fdbfcb9ccacd, register_id=5409f7c4eca9eb7182968ee1, source_name=Image Server
App 48384 stdout: source_id=5a9ed23cf493fdbfcb9ccd7f, register_id=540a0e76eca9ebd28efc4481, source_name=Image Server
App 48384 stdout: source_id=5a9ed23ff493fdbfcb9ccede, register_id=540a0e84eca9ebd28efc8c69, source_name=Image Server
App 48384 stdout: source_id=5a9ed243f493fdbfcb9cd090, register_id=562c92b2f493fdad4b000002, source_name=Image Server
App 48384 stdout: source_id=5a9ed243f493fdbfcb9cd0e0, register_id=56fc943cf493fd1c6e02616c, source_name=Image Server
App 48384 stdout: source_id=5a9ed247f493fdbfcb9cd22e, register_id=5409f4c8eca9eba20691cd32, source_name=Image Server
App 48384 stdout: source_id=5ae44a83f493fd0aa02fd361, register_id=5a2feb53f493fd98ac82f8ee, source_name=Image Server
App 48384 stdout: source_id=5ae458d9f493fd0aa0306c22, register_id=5ae458d2f493fd0aa0306c21, source_name=Image Server
App 48384 stdout: source_id=5ae46dacf493fd0aa031187e, register_id=5ae46da1f493fd0aa0311853, source_name=Image Server
App 48384 stdout: source_id=5afd53caf493fd61e75aaf90, register_id=5afd53b9f493fd61e75aaf8f, source_name=Image Server
App 48384 stdout: source_id=5b04261df493fd61e783b262, register_id=5b04260bf493fd61e783b13f, source_name=Image Server
App 48384 stdout: source_id=5b053235f493fd61e7895ab9, register_id=5b052314f493fd61e788ee4d, source_name=Image Server
App 48384 stdout: source_id=5b053266f493fd61ec17d19d, register_id=5b05226df493fd61e788ea78, source_name=Image Server
App 48384 stdout: source_id=5b055b8af493fd61e78a96e9, register_id=5b055b7ff493fd61e78a96e6, source_name=Image Server
App 48384 stdout: source_id=5bacbeebf493fd1773b54724, register_id=5ba6415bf493fd176ec69600, source_name=Image Server
App 48384 stdout: source_id=5bafd1cef493fd72687a97ff, register_id=5bafd1bff493fd72687a97fe, source_name=Image Server
App 48384 stdout: Completed 500 Internal Server Error in 344ms (ActiveRecord: 0.3ms)
App 48384 stdout:   Rendered user_mailer/batch_processing_success.html.erb (2.8ms)
App 48384 stdout: 
App 48384 stdout: Sent mail to jmeyers4@cox.net (64.5ms)
App 48384 stdout: ** [Airbrake] Unable to contact the Airbrake server. HTTP Error=Net::ReadTimeout
App 48384 stdout: ** [Airbrake] Failure: NilClass
App 48384 stdout: 
App 48384 stdout: TypeError (no implicit conversion of nil into String):
App 48384 stdout:   app/models/source.rb:92:in `+'
App 48384 stdout:   app/models/source.rb:92:in `block in get_source_ids'
App 48384 stdout:   app/models/source.rb:91:in `each'
App 48384 stdout:   app/models/source.rb:91:in `get_source_ids'
App 48384 stdout:   app/controllers/manage_counties_controller.rb:196:in `manage_sources'
```

If I'm interpreting this correctly, it looks like the server timed out on the source which causes the error, before printing off it's params - because there was a `nil` field in there.  The source_ids are in order though, so it may be possible to find the next one in line.

The problem is with the Image Server and accessing it to delete files - there's no documentation on this that I can see, and I'm unsure of the effects of deleting files in there.

I think this will have to wait for Kirk to return, unless @bev-fc can create a workaround in her existing code to render the page if there are nil fields, but that may be a large task.

**Comment by bev-fc** [comment] 2018-10-02 19:55
@smrr723 I think I can add only not nil values will run https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/source.rb#L93 to render the result except the broken one, but I don't know if I am supposed to make a detour like this over the production code.

**Comment by smrr723** [comment] 2018-10-03 13:19
@bev-fc - also unsure if adding this exception would be safe or not, so better to wait perhaps.

I will mention @Captainkirkdawson in case he is able to see this and chime in via email.

**Comment by richpomfret** [comment] 2018-10-10 16:13
@Captainkirkdawson what are your thoughts on this one?

**Comment by Captainkirkdawson** [comment] 2018-10-11 15:41
@smrr723 @bev-fc @SteveBiggs Will look at later today when the brain wakes up

**Comment by Captainkirkdawson** [comment] 2018-10-11 23:10
@smrr723 @bev-fc @SteveBiggs @edickens @richpomfret 

A mongo search  db.sources.find({source_name: { $exists: false }}).pretty() shows that

The Parish Register register for Holy Trinity in Barnoldswick of Yorkshire, West Riding has a source that contains no source name. 

It was created on September 29.
 "_id" : ObjectId("5bafd24cf493fd72687a9a8f"),
        "original_form" : {
                "type" : "fiche",
                "name" : ""
        },
        "notes" : "",
        "start_date" : "",
        "end_date" : "",
        "creating_institution" : "ManCity",
        "holding_institution" : "",
        "restrictions_on_use_by_creating_institution" : "",
        "restrictions_on_use_by_holding_institution" : "",
        "open_data" : false,
        "url" : "",
        "register_id" : ObjectId("5bafd1bff493fd72687a97fe"),
        "u_at" : ISODate("2018-09-29T19:28:12.014Z"),
        "c_at" : ISODate("2018-09-29T19:28:12.014Z")

I have added the source name to the document.

It is now possible to manage the images for WRY

I note there are no images on the image server for Barnoldswick Holy Trinity PR in WRY 

I do not know if there should be.

@smrr723   @bev-fc the diagnostic code that was added to the sources model should be removed

**Comment by edickens** [comment] 2018-10-12 08:16
Thanks Kirk.  We can now upload the images.
Does a check need to go in "Create Source" to ensure that there is a name?  I can't see how this occurred because the creation of a Source is automatic.  It was created correctly in the Images folders.
We do not have any means to enter a Source name, or edit it, or delete it.  Do you think it will happen again?

**Comment by smrr723** [comment] 2018-10-12 09:38
@Captainkirkdawson thanks, Kirk. 

@bev-fc FYI - I've removed the diagnostic log message from master with a `revert merge`, so just needs to be removed from your own branch now before your next push.

**Comment by SteveBiggs** [comment] 2018-10-12 09:48
Reiterating @edickens points, do we know:
- how/why this happened? 
- is it possible/likely to happen again?
- can anyone else fix it if @Captainkirkdawson is unavailable?

**Comment by Captainkirkdawson** [comment] 2018-10-12 13:54
@SteveBiggs 
Raised new story to research specific event to address point 1.
Cannot answer point 2 without knowing answer to point 2. 
Cannot answer point 3.

**Closed** 2018-10-24 16:22 UTC
Labels: Image, P23, Urgent, bug
