### ISSUE TITLE
All appropriate roles can create and reply to Contacts, Messages and Feedbacks System

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1380] opened 2018-01-15 16:21 UTC
Needed for GDPR (may 2018)
needs #1517
needs #1516
needs #1514
needs #1133
needs #1330

**Comment by suffolkroots** [comment] 2018-02-22 10:39
Contacts  should be automatically forwarded to COORD's email address. There  should be no need to visit the site to access messages.

**Comment by edickens** [comment] 2018-02-22 10:56
And the Coordinator should be the "To:" and anyone else "cc:" and not "bcc".  In this way we know who should reply and who has received the message.  This also helps if the Coordinator is away and CommsCoord is looking after the messages.

**Comment by SteveBiggs** [comment] 2018-02-22 14:29
I agree that Coords should be informed via email that they have a contact, but if they just reply from their personal email account to the researcher (as some coords will), there is no way that anyone else knows whether the contact has been dealt with and there is no record within the FR system of what the resolution was. Also, many counties do not have active coords (even though one may be listed in FR), so emails to them will go unanswered and no one else will know.

Once a coord is informed that they have a contact, they should access the contact on the FR site to reply so that there is traceability of the issue to resolution.

**Comment by richpomfret** [comment] 2018-03-12 16:18
All who have access to contacts should be able to reply to them within the FR Contacts system and via feedback system. Should apply to all roles.

**Comment by SteveBiggs** [comment] 2018-04-12 10:58
@Vino-S can you please ensure that the relevant CC is sent an email when a new contact comes in for their county (this to be in addition to the comm coord email address which should also remain on copy).

**Comment by Vino-S** [comment] 2018-04-12 11:02
Sure @SteveBiggs 
I will add those steps as part of my work

**Comment by richpomfret** [comment] 2018-05-09 16:13
@Vino-S Is this now complete?

**Comment by Captainkirkdawson** [comment] 2018-05-09 17:01
deployed to test3 for testing

**Comment by SteveBiggs** [comment] 2018-05-09 19:53
I can't find where the reply action is to reply to feedback or contacts. Please clarify.

**Comment by Vino-S** [comment] 2018-05-14 12:13
Hi @SteveBiggs , 
I have implemented the reply system only in our Message System. If it works as expected I will implement for Feedback and Contacts.
A **syndicate_coordinator** will have access to all the messages received for particular syndicate.
Path: Your Actions > Manage Syndicate > Select your Syndicate > Syndicate Options
In Syndicate Options select **View your messages**.

**Comment by Vino-S** [comment] 2018-05-14 12:16
Following are further details:
**userid_messages page:**
1. Created a Reply action in the userid_messages page. The
userid_messages page lists the **main_messages** for which recievers can
send a reply.

2. The userid_messages page also has button "View Reply Messages" which
will list all the **reply_messages** recieved by the user.

3. The reply action is only available to **main_messages**. The user
will not be able to send replies to **reply_messages**.

4. The Show action in userid_messages has a button "View Reples" to view
reply_messages of a main_message in show_reply_messages page .

5. The show_reply_messages has a button "View your Replies" which will
list the replies sent by the current/logged in user.

6. Remove action is enabled only for **reply_message** and for
main_messages which do not have replies.
-------

**Message System:**

1. Added an action "List Unsent Messages" which as the name suggests
will list the messages that are created but not sent.

2. The DES or the Destroy is enabled only for **reply_message** and for
main_messages which do not have replies.
---------

**reply page: (Page where user creates reply)**

1. The reply_message uses the same subject as main_message prefixed with
"Re:". Hence the subject is not writable/editable.

2. The page also lists the main_message and reply_messages for reference
when writing a reply.
---------

**Manage Syndicate:**

1. Created a "View your Messages" in Syndicate options. The action will
list the main_messages recieved for the selected Syndicate by the user.

2. In "View your Messages" page we have an action "View Reply Messages"
to view reply_messages of selected Syndicate.
-------------

**Permissions:**
**1. userid_messages page:**

Following person_roles have access to Reply Action:

system_administrator, executive_director, engagement_coordinator,
website_coordinator, general_communication_coordinator and
volunteer_coordinator.

**2. Manage Syndicate:**

Following person_roles have access to Reply Action via "View your
Messages" Syndicate Option:

syndicate_coordinator, county_coordinator, country_coordinator,
system_administrator, volunteer_coordinator, documentation_coordinator
and data_manager.

However they can send reply only to **Members of the Syndicate**.

**3. Following person_roles cannot send Reply:**

researcher, computer, trainee, pending, transcriber, technical,
contacts_coordinator, project_manager, publicity_coordinator and
genealogy_coordinator

**Comment by richpomfret** [comment] 2018-05-23 15:44
Ready for testing.

**Comment by SteveBiggs** [comment] 2018-05-28 11:03
I'm afraid I can't figure out how to test the reply system with the way it's been implemented. I think it would be easier if @Vino-S went ahead and implemented it for Contacts and Feedback in test3 so I can test it the way we are actually going to use it.

**Comment by Vino-S** [comment] 2018-06-05 14:50
Hi @suffolkroots , I had implemented Reply only for the Feedback system so far. I am working on for Contacts. I will create a new task for the same.

**Comment by suffolkroots** [comment] 2018-06-05 15:05
Thanks @Vino-S

**Comment by SteveBiggs** [comment] 2018-06-06 13:11
@Vino-S reply to Feedback seems to work, but there is a problem with the Breadcrumbs from here:
![image](https://user-images.githubusercontent.com/25303607/41040141-75f3686a-6993-11e8-976e-1037d1156c98.png)
Takes you to the main system messages.

**Comment by richpomfret** [comment] 2018-06-06 15:38
Assigned back to you @Vino-S and moved back into the sprint backlog.

**Comment by SteveBiggs** [comment] 2018-06-28 10:43
Thanks @Vino-S and will this include an email copy being sent to the relevant SC when a contact comes in for their syndicate? We still need the email to go to comscoord as well.

**Comment by Vino-S** [comment] 2018-06-28 10:55
We can add SC, CC and comscoord to the mail cc. Do they also be able to give reply to feedbacks?

**Comment by SteveBiggs** [comment] 2018-06-28 11:31
No, Feedbacks only go to my email address so only Sys Admins need reply to them.

**Comment by richpomfret** [comment] 2018-07-04 16:08
@SteveBiggs to test.

**Comment by SteveBiggs** [comment] 2018-07-04 22:00
Tested on test3 and seems to work fine. I would like to get this into production asap together with the original subject of this story - ability to reply within the message system.

**Comment by Vino-S** [comment] 2018-07-11 14:32
Hi @SteveBiggs , The ability to reply within message system is already implemented. It requires testing. Code is running in test3.

**Comment by SteveBiggs** [comment] 2018-07-11 15:16
@Vino-S the ability to reply to Feedbacks is there but I cannot see it for Contacts?

**Comment by Vino-S** [comment] 2018-07-11 16:50
Ah. Apologies @SteveBiggs . I have not implemented the Reply system for Contacts.
 I have implemented the Reply system for the messages that user receives. Below is the link:
https://test3.freereg.org.uk/messages/userid_messages

**Comment by SteveBiggs** [comment] 2018-07-11 21:33
What we urgently need is the ability for coordinators to be able to reply to Contacts for their county in the website Contacts system.

**Comment by Vino-S** [comment] 2018-07-19 16:57
Hi @SteveBiggs , implemented the ability for coordinators to reply to Contacts. Running in test3.

**Comment by SteveBiggs** [comment] 2018-07-19 19:41
@Vino-S I tried replying to a contact that was already there and it returned the error page:

![image](https://user-images.githubusercontent.com/25303607/42966147-224e9fea-8b94-11e8-90fc-cd17e020ca85.png)

**Comment by Vino-S** [comment] 2018-07-19 20:38
Hi @SteveBiggs , fixed the code and updated it in test3

**Comment by smrr723** [comment] 2018-07-24 10:35
Deployed to production.

**Comment by SteveBiggs** [comment] 2018-07-24 15:32
I just replied to a contact and although the email appears to have gone, I was sent to an error page when I clicked send:

![image](https://user-images.githubusercontent.com/25303607/43149316-1017bebe-8f5f-11e8-8063-19ac400181e2.png)

**Comment by edickens** [comment] 2018-07-24 15:53
That sounds much like what I got when sending to DOR syndicate members.

![capture](https://user-images.githubusercontent.com/8876165/43150447-dd66658a-8f61-11e8-9398-1a3d703f19f8.JPG)

I cannot confirm if it was sent as I have had no feedback and no copy came to me.  It is marked as Not sent in the message system.

**Comment by richpomfret** [comment] 2018-07-25 16:35
@SteveBiggs so it was working ok on TEST but something has broken during deployment? Does this occur when sending any batch message to members? It looks like you both have had slightly different versions of the same/similiar problem there..

**Comment by SteveBiggs** [comment] 2018-07-25 21:43
I just did a test send of a message to my Sussex and Surrey syndicate and it worked without any problems. Several have already confirmed receipt of the email.

**Comment by SteveBiggs** [comment] 2018-07-28 12:40
When a SC replies to a contact via the FR website, can a copy of the reply be automatically sent to the comscoord email address so they know it has been answered?

**Comment by SteveBiggs** [comment] 2018-07-28 12:42
Rather than having a destroy (DES) button for when a Contact has been answered, would it be better to archive the Contact so that we keep a record of it in the system?

**Comment by Captainkirkdawson** [comment] 2018-10-23 02:50
All requirements are currently addressed in test3

**Comment by Captainkirkdawson** [comment] 2018-10-23 16:30
I suspect there may be a weakness in the implementation with respect to what the various roles can see and can do

**Comment by Captainkirkdawson** [comment] 2018-10-29 23:21
running in test3

**Closed** 2018-11-19 15:38 UTC
Labels: Communication, P18, Urgent, testing
