### ISSUE TITLE
Server almost unusable

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1183] opened 2017-04-18 00:44 UTC
Mick Claxton noted: Also the server is painfully slow at the moment and has been for  at least three weeks. I am always getting Timed Out messages and it is taking a ridiculous amount of time to do admin work.

**Comment by Captainkirkdawson** [comment] 2017-04-18 04:17
Doreen Olds reported

sorry got the wrong number, there is a copy of what I see.
not able to do anything on this site.

504 Gateway Time-out

The server didn't respond in time.

Regards Doreen

**Comment by Captainkirkdawson** [comment] 2017-04-18 04:18
This is occurring 20-30 times a day and affecting all members

**Comment by SteveBiggs** [comment] 2017-04-19 14:54
I have been in email discussion with Pat about this. Pat says:

"We have (most, perhaps all) of the technical folk lined up to do the work (2 hours to get Saki replaced, 1 week to get the entire structure of the servers changed).  We are now waiting for the password so that we can do this.  So provisionally, Saki within 48 hours, and the new system by the end of next week.

I hope that I will be able to confirm this in this afternoons meeting."

Once confirmed, I'll send out a message to all on FR.

**Comment by richpomfret** [comment] 2017-04-19 15:26
Should be fixed via server reconfig. However, need to explore why this has been more of an issue recently i.e. perhaps due to the HAproxy change (and the lack of data showing us where things have been falling over). To investigate.

**Closed** 2017-04-26 16:17 UTC
Labels: committed, Performance
