### ISSUE TITLE
Link from Search Details page to Source

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#553] opened 2015-08-24 15:53 UTC
Graham Upton has suggested that people will want to find out who has the original - and this is possibly a way of 'giving back' to record offices which allow us to have free or affordable access to records.

If you delve down in Database Contents in FreeREG2, through county, place, church, and "There are transcriptions for the following register(s)" you get to a field for "Source" which I presume should say 'Midshire County Record Office' or 'The Parish of St Whosith and All Angels' or 'Midditon Borough Council', etc. depending who owns / curates the physical record and could hyperlink to those who have been helpful.  

What might need action as an enhancement is that from the search result details, while you get "For information about this place follow the link to Midditon", there is no indication that you will also find out information about who has the physical record by following that link (that is just a text change, so easy enough).  However, directing people to what they want means clicking to Midditon's page, to the church, to the record ... and if you know you want to find out about the physical record, that's a long way round, so a direct link to the register information would be more useful.

There's also a need to get the information about the records into the database in the first place ....

**Comment by Captainkirkdawson** [comment] 2015-08-24 17:44
As you note there are many fields available for the inclusion of useful information about Places, Churches and Registers. Including a link to the church website as well as information about the register. These fields never existed in FR1, in fact the whole concept of a register did not exist, nor was information available about the Place or the Church.

These fields need to be populated by coordinators and others. The edit tools are there ready to be used.

Are you suggesting that the link be to the Register rather than the Place? This is a trivial change as the links already exist to go to the Church or Place from a Register

**Comment by Captainkirkdawson** [comment] 2018-02-17 19:06
Duplicate of #1307

**Closed by Captainkirkdawson** 2018-02-17 19:06 UTC
Labels: Actor: researcher, ready
