### ISSUE TITLE
Relocate function fails in Production

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1087] opened 2017-02-04 17:45 UTC
same file as with 1086.

I was going to relocate this file as well. but same RED "OOPPS sorry etc message.

**Comment by Captainkirkdawson** [comment] 2017-02-04 18:23
Duplicate of 1085. Message about issue was placed on Member login earlier today

**Closed** 2017-02-04 18:23 UTC
Labels: bug
