### ISSUE TITLE
Bounced email not appearing in the overnight report

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1363] opened 2017-12-07 06:43 UTC

**Comment by edickens** [comment] 2017-12-07 06:48
On 1-12-2017 at 01:39 I got my two copies of the overnight bounced emails report both of which showed no bouncing emails.   But I also got this report:-
![capture](https://user-images.githubusercontent.com/8876165/33702143-3c7eb628-db1a-11e7-8e48-936672782d46.JPG)
Where does this report come from?  Has anyone done anything about this problem?  Is it just Comms who will see this and need to take action?  Is action needed?

**Comment by richpomfret** [comment] 2017-12-18 16:36
Investigate where this might be broken.

**Comment by Captainkirkdawson** [comment] 2018-08-12 19:32
Duplicate of #1264

**Closed by Captainkirkdawson** 2018-08-12 19:32 UTC
Labels: Communication, ready
