### ISSUE TITLE
Registering new transcribers in FR

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#611] opened 2015-10-21 08:15 UTC
Now that FR is live, can new transcribers register there?

**Comment by edickens** [comment] 2015-10-21 08:19
I think we should open to new transcribers so that they can register in FR.  We need the "Volunteer" Button back.  The transcriber agreement may not be ready,  so we need to cater for that.
If they cannot register into FR, they will need to register in FR1 and I want to avoid that.  E

**Comment by Captainkirkdawson** [comment] 2015-10-24 22:46
Duplicate of 529

**Closed** 2015-10-24 22:47 UTC
Labels: duplicate
