### ISSUE TITLE
Image Number flag on file header page appears to function wrongly

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1005] opened 2016-11-08 16:02 UTC

**Comment by Sherlock21** [comment] 2016-11-08 16:11
This issue was raised as a query by the SOM CC in an email to me, asking why the flay says NO when there were image numbers in the uploaded file.

I have obtained a copy of that original file front he Transcriber, uploaded it into T3 and checked the details.
the file uploaded did have the +LDS flag in the header and the file did contain file and image numbers in it.
The file uploaded OK
viewing the file headed online, accessed from the County/ Placename/ church name/  it did show NO to Image numbers.

but browse in Batch online, showed image numbers.
Downloading a co;y of the batch, produced a file that had the original image numbers in it, 

returning to the online version of the record, the file header page NOW shows Image numbers YES.

So why did the flag say NO when clearly there were image numbers present?
and what changed the flag from  No to Yes when I downloaded the batch?


the copy of the file is in T3. it is newly uploaded and processed today. it has not been edited online at all.
Place is SOM / Ilminster
church is St Mary TR.
file is VicRyall.SOMILMBU5.csv

ignore bits of the header referring to Yorkshire WRY.

**Comment by Captainkirkdawson** [comment] 2016-11-09 00:12
Should anyone investigate this issue. The lds flag is a "yes" or "no" field with "no" as the default. (It is not a boolean field although it likely should have been) It is set to "yes" by the new update processor if the 5th header line of a file contains +LDS, We removed the ability to edit the field on-line a few weeks ago.

**Comment by Sherlock21** [comment] 2016-11-09 08:35
I perhaps should have added at the start, that this file was uploaded after the system came back this week. so it was under the new process.

**Comment by Captainkirkdawson** [comment] 2016-11-09 23:32
I think it is time we adopted EricD suggestion. We process all entries as if there were image numbers present. It matters not to the data  processor.  When downloaded the image numbers will be added even if they are blank.

It will not matter if the +LDS is there or not. We will process the appropriate fields. 

 I would prefer not to add a +LDS flag but if we did we would add to ALL.

The only question is whether or not WinFreeREG needs the +LDS flag in a file for it to process the image numbers . If Mike can process a file without it so much the better. WinFreeREG can either add blanks or not depending on how best the app works

**Comment by Sherlock21** [comment] 2016-11-10 08:26
I would go along with that idea.

Simple works best.

**Comment by edickens** [comment] 2016-11-10 12:21
I'm pretty sure that WinFreeREG (and WinReg) do not mind if +LDS is
    there or not.  But if not you cannot enter Film and Image numbers. 
    It will generate it as soon as you enter even a space in the Film
    and Image numbers.  But if +LDS is there, then there needs to be the
    correct number of commas, although perhaps that was more of a F1
    problem.  WinReg ensures that the commas are there.
    
    E
    
      On 09/11/2016 23:32, Kirk Dawson wrote:
    
    
      I think it is time we adopted EricD suggestion. We process all
        entries as if there were image numbers present. It matters not
        to the data processor. When downloaded the image numbers will be
        added even if they are blank.
      It will not matter if the +LDS is there or not. We will process
        the appropriate fields. 
      I would prefer not to add a +LDS flag but if we did we would
        add to ALL.
      The only question is whether or not WinFreeREG needs the +LDS
        flag in a file for it to process the image numbers . If Mike can
        process a file without it so much the better. WinFreeREG can
        either add blanks or not depending on how best the app works
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1005: I think it is time we adopted EricD suggestion. We process all entries as if there were image numbers present. It matters not to the data  processor.  When downloaded the image numbers will be added even if they are blank.\n\nIt will not matter if the +LDS is there or not. We will process the appropriate fields. \n\n I would prefer not to add a +LDS flag but if we did we would add to ALL.\n\nThe only question is whether or not WinFreeREG needs the +LDS flag in a file for it to process the image numbers . If Mike can process a file without it so much the better. WinFreeREG can either add blanks or not depending on how best the app works"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1005#issuecomment-259557760"}}}

**Comment by EmJayFry** [comment] 2016-11-11 17:04
From my end of things, this is how it currently works.

New Files
When a new file is created, the user is offered the opportunity of including th +LDS header or not. A check-box is used to convey the answer. If the +LDS header is to be included, WinREG and WinFreeREG will allow the user to enter data into the two extra columns - generally labelled as Fiche and Image. These then become the last two fields in each data record. If no data is entered, then two empty fields are included where appropriate.

Existing Files
WInREG allows the user to add the +LDS header to a file that currently doesn't contain it and to remove it from a file that does. WinFreeREG does not possess this ability. In other words, the presence of the +LDS header is set only at file creation time. Of course, manual tampering of the file outside of either program is possible with the usual warnings about undesired results when the user knows not what they do. This change in behaviour for WinFreeREG is based solely on the fact that the user should know at the very outset of a new file whether the +LDS header will be relevant or not.

**Comment by Captainkirkdawson** [comment] 2016-11-12 15:41
Yes but what does WinFreeREG do if it receives a file that has the image fields included but NO +LDS.

As stated earlier but paraphrased. 

FR does not need a +LDS to tell it to process the image fields. We will process the fields regardless.
The +LDS was there only for FR1
Can we get rid of the +LDS?  It will natter not if it is in a file it will just be ignored.

The issue is what happens on a download the image fields will ALWAYS be included but do we have to include the +LDS for WinFreeREG?????. 
I would prefer not to add a +LDS flag but if we did we would add to ALL.

The only question is whether or not WinFreeREG needs the +LDS flag in a file for it to process the image numbers . If Mike can process a file without it so much the better. WinFreeREG can either add blanks or not depending on how best the app works

**Comment by EmJayFry** [comment] 2016-11-12 22:17
On 12 Nov 2016 17:41, Kirk Dawson wrote:

Taken a few days off and didn't understand what all the kerfuffle was about :-)

> Yes but what does WinFreeREG do if it receives a file that has the image fields
> included but NO +LDS.
>
> As stated earlier but paraphrased.
>
> FR does not need a +LDS to tell it to process the image fields. We will process
> the fields regardless.
> The +LDS was there only for FR1
> Can we get rid of the +LDS? It will natter not if it is in a file it will just
> be ignored.
>
> The issue is what happens on a download the image fields will ALWAYS be included
> but do we have to include the +LDS for WinFreeREG?????.
> I would prefer not to add a +LDS flag but if we did we would add to ALL.
>
> The only question is whether or not WinFreeREG needs the +LDS flag in a file for
> it to process the image numbers . If Mike can process a file without it so much
> the better. WinFreeREG can either add blanks or not depending on how best the
> app works

Okay! I think I understand what you're asking.

If a file is downloaded to WinFreeREG (we can ignore WinREG for now) it gets 
stored "as is". Exactly as you provide the data. If you include the two extra 
fields but not the +LDS header, then that is how the data gets saved. 
Subsequently, if the file now gets edited, because there is no +LDS header, the 
extra fields will be ignored when the file is loaded into the program. If the 
file is now edited and re-saved, there will be no +LDS header and there will be 
no extra fields.

I guess the same would apply to WinREG, but the downloading would be slightly 
different in that the user would need to display the file and then copy the data 
to the clipboard and create a file from there. WinREG could then access the file 
and be able to process it exactly as in WinFreeREG above.

What we need to do is drop the +LDS header and make the two fields a normal part 
of any record. At the same time WinFreeREG doesn't need any major changes for 
this. The users already possess the ability to make use of these fields or not. 
The only thing that needs some consideration on my part, is how to handle the 
automatic replication of Fiche and Image data from a previous record - since 
this facilitates data entry, the replication is quite useful.

-- 
Regards,
Mike Fry (Jhb)

**Comment by richpomfret** [comment] 2016-11-14 16:37
This doesn't appear to affect the system operation at all so will close the issue. If we feel there is a separate or worthwhile task here, we can create a separate and more specific story.

**Closed** 2016-11-14 16:37 UTC

**Comment by Sherlock21** [comment] 2016-11-14 18:24
Why not then just remove the display?
A small effort, but then at least the viewers don't get confused.
