### ISSUE TITLE
Test3 Refinery Suppresses Styles

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#870] opened 2016-07-14 01:59 UTC
Second issue:

I often place style scoped="scoped> </style> block at the top of a page -- or anywhere it is needed. Most of these will ultimately become redundant as we add the styles to our own stylesheets, but they are extremely useful in the meantime.

Refinery is rendering the content of these style blocks on the html page and failing to apply the styling -- disaster.

A
![freereg](https://cloud.githubusercontent.com/assets/2874694/16825712/39b6aeec-4934-11e6-9018-f493cd3402d8.png)

**Comment by Captainkirkdawson** [comment] 2016-07-14 02:01
Issue 2 (style block content is treated as text and dumped on page) would break a good many of the/my Refinery pages: we cannot update the system without a workable plan to deal with this. These are the options as I see them:

Gather all the styles I have created and add them to our stylesheet: would need careful preparation and checking

Convert all the additional styling to inline style="" statements and copy them to all the relevant elements -- very time-consuming and error-prone for a page such as Entering data from registers and completely un-DRY (wet?!?)

Abandon all my CSS and present pages with supplied styling only: difficult to imagine how bad some of the pages would look and/or how much effort would be needed to make said pages "work" acceptably (the table on Behind the scenes would have to go.)

**Comment by Captainkirkdawson** [comment] 2016-08-06 16:51
Solution to this issue is holding up deployment of the mongoid5 branch

**Comment by benwbrum** [comment] 2016-08-08 21:09
Refinery appears to be stripping out the `style` tags Allison is editing.  In the sandbox page, she's entered this:

```html
<style scoped="scoped">
  q.typo::before { content: '\201C'; }
  q.typo::after { content: '\201D'; }
  figcaption { font-size: smaller; font-style: italic; } /* This is a comment */
</style>
```

This is rendered in the browser as this:
```html
<section id="body"><div class="inner">
  q.typo::before { content: '\201C'; }
  q.typo::after { content: '\201D'; }
  figcaption { font-size: smaller; font-style: italic; } /* This is a comment */


<p>Quotations:
```

I believe that this stripping is the root cause of our problems here.  That does not yet give me a good path to understanding what's causing the stripping, but that's next.

**Comment by benwbrum** [comment] 2016-08-08 21:16
There is a decent chance this can be fixed by whitelisting `style`, though that may still be a challenge -- see https://github.com/refinery/refinerycms/issues/2141

**Comment by benwbrum** [comment] 2016-08-09 00:16
I have determined that the `script` tag is correctly being saved to the database, so the problem is not with the editor  Next question: what does Refinery do when it's rendering?

**Comment by benwbrum** [comment] 2016-08-09 13:55
It turns out there is a separate scrubbing/sanitization process that uses a different whitelist, at https://github.com/refinery/refinerycms/blob/master/pages/app/presenters/refinery/pages/section_presenter.rb#L71

The game's afoot!

**Comment by benwbrum** [comment] 2016-08-09 14:22
That's definitely what's causing the problem.  Here's what I see on my console:
![refinery_sanitized_warning](https://cloud.githubusercontent.com/assets/199961/17519680/93ab9b36-5e12-11e6-8e4e-a863988b280c.png)

**Comment by benwbrum** [comment] 2016-08-09 14:26
It turns out that there are a lot of new sections of the refinery initializer code that were added between our deployment and the new version.  It's going to take some teasing to get them merged into our code.

**Comment by benwbrum** [comment] 2016-08-09 18:04
I've updated all the refinery initializers and added `style` and `scoped` to the whitelist.  @AlOneill, are there any other tags you use which aren't included in https://github.com/flavorjones/loofah/blob/v2.0.3/lib/loofah/html5/whitelist.rb#L49 ?

**Comment by AlOneill** [comment] 2016-08-10 12:29
html tag list looks fine

content and list-style-type are missing from the ACCEPTABLE_CSS_PROPERTIES

The list-style-type keywords  are missing from ACCEPTABLE_CSS_KEYWORDS, as are smaller, lighter, inline-block

The Roles table uses a couple of transforms:
            -ms-transform: translate(10px, 51px) rotate(315deg);
            -moz-transform: translate(10px, 51px) rotate(315deg);
            -o-transform: translate(10px, 51px) rotate(315deg);
            -webkit-transform: translate(10px, 51px) rotate(315deg);
            transform: translate(10px, 51px) rotate(315deg);

I have also used a counter on a long list: counter-reset, counter-increment (properties); split, counter(split)  (keywords)

That is probably all -- will reassess when production pages have been copied to test3.

**Comment by Captainkirkdawson** [comment] 2016-08-10 14:19
See  my other note test3 had a full copy of the refinery pages taken about
a month ago.
My plan had been to get them all correct and then copy back to production

**Closed** 2016-08-10 14:45 UTC
Labels: Urgent
