### ISSUE TITLE
'Convert to Issue' button in Contacts returns red error

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2335] opened 2020-11-14 13:57 UTC
Tried in both Edge and Chrome and get the "Something went wrong ... " message.

**Comment by Captainkirkdawson** [comment] 2020-11-25 16:58
Caused by a change in Github authorization

**Comment by PatReynolds** [comment] 2020-11-25 17:08
Issue fixed, so closing.

**Closed by PatReynolds** 2020-11-25 17:08 UTC
