### ISSUE TITLE
Contacts Coordinator Actions

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#770] opened 2016-04-13 13:52 UTC
I request a change to the way Contact messages are processed.

**Comment by edickens** [comment] 2016-04-13 14:13
You will have seen the message with a description of the Role of Communications Coordinator aka Contacts Coordinator?  We have found someone, and an assistant, to do this work.
The idea is that all Contact (and Feedback?) messages go to the Communications Coordinator who will check the message, do a standard reply if applicable, then forward them to the correct person if necessary.
So Contact messages only need to go to Communications Coordinators, with a copy to  System Administrators, at least for now.
To do this anyone assigned Contacts_Coordinator should have Actions to view and destroy Contact messages, be able to view all UserID, CC and SC names so as to obtain their latest email addresses.
I'm not sure if we want to do this for Feedback messages as well.  And should the Communications Coordinator also convert these messages into an Issue if they think that is necessary?
And have I understood what was intended for the "Contacts_Coordinator" or is Communications Coordinator something else?  E

**Comment by PatReynolds** [comment] 2016-04-18 08:56
Not sure what milestone to put on this - if the emails that used to go to Damien now go to the two coordinators - leave this as a development question (1.5)?

**Comment by edickens** [comment] 2016-04-18 12:19
The problem with V1.5 is that it is six months away and we need to
    change the distribution of emails and the Actions available to the
    CommsCoord pretty soon.
    
    E
    On 18/04/2016 09:56, PatReynolds wrote:
    
    
      Not sure what milestone to put on this - if the emails that
        used to go to Damien now go to the two coordinators - leave this
        as a development question (1.5)?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by PatReynolds** [comment] 2016-04-27 16:51
Hmm I think we need to treat this as 'business as usual' i.e. not a development issue or a bug issue, but the kind of request that will become everyday, going forwards.  Kirk, could you action the change of address and change of routing?  Anything else can be left to 1.5.

**Comment by Captainkirkdawson** [comment] 2016-04-30 15:32
This is duplicate of 775 which has already been actioned

**Closed** 2016-04-30 15:32 UTC
Labels: Actor: executive, duplicate, enhancement
