### ISSUE TITLE
Citation pop up window (Citations phase 2)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1889] opened 2019-04-12 13:44 UTC
I would find it helpful if the citation appeared in a pop-up window (rather than a separate tab) with a big 'Copy' button which (when pressed) causes the citation to be copied to the clipboard.

Needs#1374

**Comment by Captainkirkdawson** [comment] 2019-04-12 17:18
Duplicate of #1887

**Closed by Captainkirkdawson** 2019-04-12 17:18 UTC
Labels: Citation Generator
