### ISSUE TITLE
Navigation down list to edit data now returns to start of list instead of Last used place, as before.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#763] opened 2016-03-30 18:44 UTC
When editing a collection - say of Place names to add some detail - eg Location ref url -  and working from a list of many to do, it used to be the case that using breadcrumbs, one went back to the record one came from.
this is no longer the case. 
so in a County / letter group with very many places, it takes for ever to scroll down again to the place one came from just to get back to where one was. 

Please restore the GO BACK TO WHERE I WAS BEFORE type of link.IfIts been a matter of Delete a Placename ( ie disable it) then go back to the one prior to where i was, as that will now have gone of course.

**Comment by Sherlock21** [comment] 2016-03-31 07:57
As Doreen points out: this problem applies also to other worklists that one needs in a list - like all the batches for a userid that one needs to go through.
Or all the batches for a Placename.

**Comment by Captainkirkdawson** [comment] 2018-08-09 23:28
Duplicate of #731

**Closed by Captainkirkdawson** 2018-08-09 23:28 UTC
Labels: Actor: county coordinator, ready
