### ISSUE TITLE
Exclude training batches

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#438] opened 2015-03-25 15:28 UTC
The work of a new transcriber does not want to be available for searching

**Comment by edickens** [comment] 2015-03-25 15:37
Any batch uploaded by a transcriber registered in the "Training" syndicate should  not be searchable but should be visible to a CC and SC for checking.  All these files should be deleted by the transcriber before they are moved out of "Training" unless they have done some actual work, in which case the batches should become searchable.
But there may be better ways of handling this, such as having a county called "Training".  This needs debate.
But at present, new transcribers training work in FR1 will be copied across to FR2.  This should be ignored if the UserID syndicate is "Training".  As soon as the UserID is moved out of "Training" then there is no more need to ignore their work and they should have deleted all training work in FR1.
EricD

**Comment by Sherlock21** [comment] 2015-03-25 16:58
A good point, EricD. These must not get mixed with genuine records.
But do we need to preserve these training records in case of needing to go back to them?
If so, May be best in a proper County & Place name  but just not shows in any public listing rather than   in a County & Place of their own that is not visible - since having a County that is not in Chapman's list was not the way to go, when I suggested creating a County called Ainsty of York to solve a different issue.  

This one reminds me: We do have many test place names &  files, from the various bits of practising that we have done. How are these to get removed?

**Comment by Captainkirkdawson** [comment] 2015-03-26 14:36
Duplicate of 290

**Closed** 2015-03-26 14:36 UTC
Labels: enhancement
