### ISSUE TITLE
Test the updated application/Mongodb application

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#848] opened 2016-07-02 14:50 UTC

**Comment by Captainkirkdawson** [comment] 2016-07-02 14:58
Need to test updated application/Mongodb on test3
Initial set of issues
Download
geo_near_distance
search_queries/report?
WinFreeReg

**Comment by edickens** [comment] 2016-07-02 15:00
Has Mike's problem accessing Test3 been solved because I don't want
    to ask others to test it if there is an access problem?  E
    
      On 02/07/2016 15:50, Kirk Dawson wrote:
    
    
      Assigned #848
        to @edickens.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Captainkirkdawson** [comment] 2016-07-02 15:05
Not yet I have only just got up

**Comment by edickens** [comment] 2016-07-02 15:15
Is the problem then just with the WinFreeREG interface?
    
    Does the testing need to be to all Actions because of the change of
    database packages?  If so I can ask them to test those and not
    WinFreeREG for now.
    
    E
    
    On 02/07/2016 16:05, Kirk Dawson wrote:
    
    
      Not yet I have only just got up
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Sherlock21** [comment] 2016-07-02 19:13
testing T3 and intended to do edin a batcg online.

Logged on OK
I got an unusually big collection of different a actions!





However: plod on and see where we get to.

Picked Manage Counties and WRY. got the usual Left hand side list.

went for Active places and got OOOPs Sorry again and failed.

Started again from a complete clear out .
tried the ALL Places this time - same result.


*****
wrote this first part of the note then cleared out the caches and everything and started

******

this time round I got my normal Actions at logon - have you chaged profiles in the last 2 minutes?

EB

**Comment by Sherlock21** [comment] 2016-07-02 20:00
more T3 testing


SNAG.

in my own list of Batches, the Info flags that were on top of the columns, to remind us of what the abreviations mean, have dropped off.

SNAG

there is now NO warning on DELETE the batch
and even though the message comes back that its been deleted the batch does not drop out of the losing.

SNAG

DOWNLOAD does not function - it just crashes out with the OOOOps SORRY…. message.




OK:-

SHOW works and then those items off it.
EDIT HEADERS works OK
ERRORS i cant test as I have none handy!
DM LOCK & UNLOCK seems ok but as they are my files I am never sure which takes priority.
RELOAD/REPLACE batch: part 1 works if i try and upload the wrong file name - it rejects it.
	=part 2 Also appears to work OK if I pick the right file name its accepted for processing now of overnight -I picked NOW. But I have not got the expected email.
But the Date of Upload has changed to today correctly.


SO conclusion of testing Batches listing and online processing from this listing.

Might  try same form the Place/church/ files start point for another userID tomorrow,


enough for you to be getting on with here!

EB

**Comment by Captainkirkdawson** [comment] 2016-07-02 20:04
WRT have you changed profiles in the last 2 minutes? No

**Comment by Sherlock21** [comment] 2016-07-02 22:03
Then there seems to be another issue: why did I get one ( new, more extensive) profile for a couple of logon's and then on the third logon, I get my normal profile. All with my same one and only userid & PW?

Screen print of what was in each of the 2 Actions Lists at logon, we in emails direct to Kirk.

Closing down now. its bed time here.

**Comment by Captainkirkdawson** [comment] 2016-07-02 22:09
Received no emails

**Comment by Captainkirkdawson** [comment] 2016-07-02 23:41
Fixed the Active and All; was an incorrect breadcrumb link

**Comment by Captainkirkdawson** [comment] 2016-07-03 03:51
Suggest you wait until Monday before testing again to give time to resolve current set of issues

**Comment by Sherlock21** [comment] 2016-07-03 08:59
As you advised me that you had fixed the All Places or Active places access, i had a look.

I don't like the style of repeating on every line, the Place name and the Church name. 
If its a slight snag that this has changed, please take on board.

If this is an intended change however, then I find it is much easier  to scan down a list only looking for the "Next" place or church, with the duplicated being omitted Please change it back.

**Comment by edickens** [comment] 2016-07-03 09:11
Hi EricB,
    
    We have had people say that they did not like the ditto marks,
    perhaps hence the change.  I agree with your suggestion.
    
    But it does raise the question as to how we make changes.  We must
    not react to the opinions of a vocal few.  However, I don't know how
    we get a majority opinion.  Perhaps we need to just leave things as
    they are for now, because we have a lot more programming to do,
    instead of spending time reacting to opinions.
    
    This is a general policy comment and I would not want to stop you
    giving your opinion, but we need to manage change better.
    
    Cheers
    
    EricD
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 03/07/2016 09:59, Sherlock21 wrote:
    
    
      As you advised me that you had fixed the All Places or Active
        places access, i had a look.
      I don't like the style of repeating on every line, the Place
        name and the Church name. 
        If its a slight snag that this has changed, please take on
        board.
      If this is an intended change however, then I find it is much
        easier to scan down a list only looking for the "Next" place or
        church, with the duplicated being omitted Please change it back.
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Sherlock21** [comment] 2016-07-03 09:32
morning, EricD

But I never get any ditto marks on my view!
the duplicate names were omitted like they woudl be in any schedule!

So is that  a feature of using a tablet or a smart phone? - both no good for using by me or by most CC’s I would have thought.

I would consider that ALL my effort on FR is based around the use of this start point - either  the All Places or the Active places list, for ALL Counties
And I was not consulted - which miffs me a bit.

I have seen a request by someone - cant remember who - to get rid of ditto marks - but as i never see them, it meant nothing to me. Perhaps their action should have been to use a device that did not create ditto marks out of nothing.

? tail wagging the dog again?

As it is, this will drive me nuts.

Eric B

**Comment by Sherlock21** [comment] 2016-07-03 09:35
Eric D

screen print off T2 for WRY/ KIPPAX and LEEDS with just blank. no ditto makks in sight.




EB

**Comment by Captainkirkdawson** [comment] 2016-07-03 14:36
There was a formal consultation with the user community on the Transcription pages where ditto marks were used instead of the blank in the Places . (The same code is used in both the public and private displays) That consultation said people preferred to have the Place and Church names repeated.
The display was adjusted accordingly.

Personally I prefer the tables without the repetition of the place and church names; it is much easier to see changes which is why I originally wrote it the way I did. But it appears that researchers do not.

As stated above it is the same code for both private and public display of our data. Duplication of the code is not a good idea from management perspectives. Code could be added to check who is displaying the table and react accordingly.

However is this just the view of Ericb and myself????? what do the coordinators think????

**Comment by edickens** [comment] 2016-07-03 14:42
I think the problem is that people do not take time to get used to a 
change.  When we first launched FR2 there were lots of complaints about 
the layout and the colour.  I also think it has a lot to do with giving 
time to be sure that we have the right solution.  Ideas like this should 
be logged and included in future versions so that we can move on.

**Comment by Sherlock21** [comment] 2016-07-03 16:58
Having just been pointed to the place where these ditto marks are used, i see no problem with them there, in the listing of churches and registers for a place ( looking at what FR production looks like.)
So I would not have supported swapping the ditto marks for full names neither here in transcription lists nor all over the other listings where  the duplicates have now been shown in full in T3.

I think Kirk had it right the first time.
Now  this "Fix " makes the application unusable by those who have to use the much bigger places  & churches lists all the time.

I can see why Kirk does not want to have virtually the same code in 2 different places, but the present solution to a moan by some, about ditto marks, is not the right reaction.

What were the statistics of the User survey that was carried out please? was it done on Github or my individual emails. - not all CC's have Github access

 If Kirk & myself are the only ones who are upset about it, then I suppose there are always 2 solutions open to us.

**Closed** 2016-08-23 14:30 UTC
Labels: Actor: technician
