### ISSUE TITLE
File not processed for some unknown reason

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#800] opened 2016-05-12 15:02 UTC

**Comment by edickens** [comment] 2016-05-12 15:18
This report was created last night.  There is no reason and it does not say that any records were rejected.....
******************************************************************* <br>
Started on the file warwhiba02.csv for SpanishKen at 2016-05-12 01:41:25 +0100. <p>
Code set 
Checking for undefined with 
Created  0 entries at an average time of ms per record at 2016-05-12 01:41:29 +0100. <br>
******************************************************************* <br>
Ken has passed a copy of the file to me and I cannot see why it was rejected.
The header rows have extra commas, which he is removing and will try again tonight.
Also the Place and Church are in uppercase, but should match in lowercase.
Any ideas?  E

![capture](https://cloud.githubusercontent.com/assets/8876165/15219674/93b50c08-185c-11e6-9de5-2397f20d6482.JPG)

**Comment by Sherlock21** [comment] 2016-05-12 18:03
Did it fail because the Church name is in CAPS? 
It created a place name in FR all in Caps which is a surprise - but no batch attached.

So more questions raised than I see answers or reasons to just close this one?

**Comment by edickens** [comment] 2016-05-12 21:50
From what EricB says, it looks as if uploaded files are creating churches, which they should not do.  I will check in more detail tomorrow, but EricB is away for a week.  ED

**Comment by Sherlock21** [comment] 2016-05-13 07:15
All I have time to share with you is: look at this in the FR application on screen. for WAR/ Whichford.

What is shown there in Caps was not input by me.
and nor was the Parish Register title either.

**Comment by edickens** [comment] 2016-05-13 09:55
WAR/Whichford,St Michael has got in a muddle.
![capture](https://cloud.githubusercontent.com/assets/8876165/15244273/4951074c-18f8-11e6-8869-a95dce002fca.JPG)
The file warwhiba2.csv has created an upper case church with register type Parish Register, even though no PR was entered.

As I said in my first comment, the commas in the header will be removed and the file uploaded again, but the same error message has occurred.  I suspect it is the capitals in the Place and Church which are not matching and causing the problem.  E

**Comment by Captainkirkdawson** [comment] 2016-05-21 01:03
The church name ST MICHAEL was create on 17 Apr. It was NOT created by the new processor as the latter was not in operation until 28 Apr. It did not create a PR either.

There was a problem caused by the capitalization of the place name. While this was successfully matched with the place name on the website  (Lower case match), the original (upper case) place name  was used when attempting to find the appropriate church name and it failed to find the church.

**Comment by Captainkirkdawson** [comment] 2016-05-21 01:04
Fixed

**Closed** 2016-06-18 14:21 UTC
Labels: bug, Urgent
