### ISSUE TITLE
Change Register Type function fails ( in Production)

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1086] opened 2017-02-04 17:43 UTC
I tried to change Reg type on the file: Amanda.CONGRAMA [ 200 records only]
but get the dreaded red "oops sorry something seems to have gone wrong"

see also next report

**Comment by Captainkirkdawson** [comment] 2017-02-04 18:23
Duplicate of 1085. Message about issue was placed on Member login earlier today

**Closed** 2017-02-04 18:24 UTC
Labels: bug

**Comment by Sherlock21** [comment] 2017-02-04 22:39
Yes, I agree it works fine for Data Manager profile too now.
