### ISSUE TITLE
Church Denomination should be a verified field backed by a table ( created by Managers) so that consistency is maintained from the start. This is a freeform field at present. not many values in it as there was no such thing in F1. But will shortly need to be populated to maintain structure of the data and ultimate searchability

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#376] opened 2015-01-10 16:17 UTC

**Comment by Sherlock21** [comment] 2015-01-13 16:28
This could be merged with :#377?

**Comment by Captainkirkdawson** [comment] 2015-01-13 17:42
Duplicate of 377

**Comment by Captainkirkdawson** [comment] 2015-01-14 16:25
Church of England
Roman Catholic
Episcopal
Wesleyan Circuit
Jewish Tabernacle
Jerusalem Salem
Welsh Non-conformist
Anglican
Church of Scotland
Free Church
Public Cemetery
Quaker
Strict Baptist
Baptist
Welsh Calvinistic Methodist
Maesyberllan Particular Baptist Chapel
Bethania Independent
Bethlehem Welsh Calvinistic Methodist
Tredustan Independent
Church in Scotland (- it seems the correct version of Church of Scotland)
Church in Wales
Non-conformist
Zionist
Mormon
We should start with the main denominations, and have Group names for each the minority types for the moment
The main thing is that the list should be amendable by the Data Manager.

**Comment by Sherlock21** [comment] 2015-01-14 16:53
The feature should also cater for UNKNOWN. or a blank space or both?

**Comment by Captainkirkdawson** [comment] 2015-05-18 21:08
ericd list
Church of England, Anglican, Baptist, Independent, Congregational, Methodist, Roman Catholic, Jewish, Quaker, Presbyterian, Unitarian, Moslem, Community Cemetery, Unknown, Latter Day Saints, Christadelphian, Evanjelical, Jehovah's witness, Christian Centre, Moravian, Zion, Salvation Army, Amani Centre, Gospel Centre, Free Church, Christian Bretheren, Buddhist Centre, Mission, Swedenborgian, First Church of Christ Scientist, Greek Ortodox, Russian Ortodox, Epsicopal, Welseyan, Calvanastic Methodist.

**Comment by Sherlock21** [comment] 2015-05-19 07:46
Would it not be wise to make this a searchable field for subsequent research, and therefore codify the titles? Easier to do now at the start, than in a future year? [Even if its not used for future statistical research]

**Comment by PatReynolds** [comment] 2015-08-11 12:00
Is there an existing listing we could use?  
I don't like 'Community Cemetery' and 'Public Cemetery as these are not faiths - and some do have specific sections for specific faiths, so we might know that some people identify as Muslim, Moravian, etc. but that others are 'unknown'.  Cemeteries might be one exception where the transcriber gets to choose the faith, rather than it being applied as a blanket to the whole register or other document.
 Is 'Christian centre' a particular family of non-conformists, or simply a term which is used by many Christian denominations - if the latter, then 'Christian' should be used.  There are many 'Amani Centres' around the world, and those that I found, if they had a faith component at all, were not specific to one faith, so think that we might need 'Unspecified Faith' to replace this, and similar places.  If we know a specific Amani centre is Christian (or RC, or ...) then we can classify it as that.  'Buddhist Centre' should be Buddhist.  'Mission' is, I think, like 'Minster', and 'Temple' a particular type of religious institution  rather than a faith.

**Comment by Sherlock21** [comment] 2015-08-11 14:59
The Public Cemetery title was my choice, and Community Cemetery was EricD's choice for the same place. Either way it's an a-religious location for public burial isn't it - as distinct to those attached to places of worship. So needs a title of some suitable word.
Its a Place at the structural level below County / Place.
What would you use Pat? 

The remaining religions were added in to cater for the future - But Public Cemetery: we have already.

**Comment by Captainkirkdawson** [comment] 2016-04-25 00:27
The ability to add/edit and delete entries in a denominations collection has been added to test3. Management is restricted to system_administrators and data_managers.
The church creation and edit screens now offer a pick list populated from the denominations collection. The default option is pre-set as "Church of England"

**Comment by edickens** [comment] 2016-04-25 06:29
Tried to edit the denomination...
    
    but no pick-list (probably needs populating so not a problem) and
    after updating, this denomination does not show.  Was not saved.
    
    Also, all listings of Place and Church should now have a column for
    Denomination so that we know which have been done.  ED
    
    On 25/04/2016 01:27, Kirk Dawson wrote:
    
    
      The ability to add/edit and delete entries in a denominations
        collection has been added to test3. Management is restricted to
        system_administrators and data_managers.
        The church creation and edit screens now offer a pick list
        populated from the denominations collection. The default option
        is pre-set as "Church of England"
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by edickens** [comment] 2016-04-25 06:33
Further to my last email.  Seems to work now that I have been out of 
that Church and back again.  Is also OK for other Churches.  But showing 
the Denomination on Place/Church listings is important.  ED

**Comment by edickens** [comment] 2016-04-25 06:40
Have created Denominations and done a few.  All seems to work OK. ED

**Comment by Captainkirkdawson** [comment] 2016-04-25 13:43
Which display do you suggest that denomination is added to and why. We must not overload already busy displays. Sounds more like a requirement for a report.
Regardless such a requirement was not part of this story and should appear as a new story

**Comment by Sherlock21** [comment] 2016-04-26 16:54
I tried the Create New Denomination tool. fine for me, but plead make it re-sort into Alphabetical order, ager any new addition.
It will get very higgledy piggledy in due course, as it appears to be in "As Created" order at present.

**Comment by Captainkirkdawson** [comment] 2016-04-26 17:39
Index now sorted.
Have real reservations about taking one field of a place/church/register and displaying on the index listing. Where would one stop. Why pick this one why not some others? The display is already noisy.

**Closed** 2016-05-04 16:29 UTC
Labels: Actor: county coordinator, enhancement, Urgent
