### ISSUE TITLE
Create Chapman Code in FreeREG for Shipping and Overseas

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1962] opened 2019-06-19 16:32 UTC
We will have some images for entries at Sea and need a separate code for them, the same as used in FreeCEN.

In FreeCEN:
OVB means born a British Subject (anywhere) or born in the British Empire (at that time).  OVF means born overseas, but not OVB.

@PatReynolds to check with @FreecenBren on the Shipping code

E2 U3 S6 C7 :P18

**Comment by Captainkirkdawson** [comment] 2019-06-21 22:57
@edickens we can activate any or all of 
'England and Wales Shipping' => 'EWS',
      'Out of County' => 'OUC',
      'Overseas British' => 'OVB',
      'Overseas Foreign' => 'OVF',
      'Scottish Shipping' => 'SCS'

What is your desire?

They would appear as a Special Grouping at the end

**Comment by edickens** [comment] 2019-06-22 07:59
I'm not very keen on any of those.  My reason is that I am not sure that we can divide the entries in that detail.  The entries we have do not state the nationality nor the country of the shipping.
I've looked on Google and cannot find a general code for Shipping or Overseas.
As a matter of interest Google found us...
![Capture](https://user-images.githubusercontent.com/8876165/59961166-e99a8280-94cb-11e9-805e-5eef573dade0.JPG)

**Comment by Captainkirkdawson** [comment] 2019-06-22 14:26
Those are the ones defined for CEN. 
What is wrong with 'Out of County' => 'OUC', 'England and Wales Shipping' => 'EWS',

**Comment by edickens** [comment] 2019-06-22 15:51
OUC usually means that the person is temporarily somewhere else.  I'm thinking of those resident overseas.
EWS would indicate to a researcher that we are sure that they are from England or Wales.
Similarly we do not know for OVB and OVF.
But perhaps we should go for OVB and EWS and leave it to the researcher to find out more.  The records I've seen do not give much information.

**Comment by AlOneill** [comment] 2019-06-22 16:11
'OUC' has a very specific meaning as used on CEN: it applies to the 1841 census where the enumerator had to answer the question 'born in (census) *county*' (emphasis mine) with either 'Yes' or 'No'. As such, I agree that it does not seem suitable here.

'EWS' and 'SCS' apply to the census *port* of the vessel: they are not used to indicate a person's place of birth.

**Comment by Sherlock21** [comment] 2019-06-22 16:17
a) as regard the British citizens who are registered at Overseas Embasies and/or Cosulates,
I would have gone for Overseas British - for baptisms, Marriages and Births

b) and perhaps for burials at sea, use the EWS  and SCS.

as regards a) would you be expecting Placenames? or will it be determined in  FR that we only work at ‘Country level’ for these type of records?
and will it be logical to allow a mix of existing counties AND one of these oversees counties at the same time?


On 21 Jun 2019, at 23:57, Kirk Dawson <notifications@github.com> wrote:

@edickens we can activate any or all of
'England and Wales Shipping' => 'EWS',
'Out of County' => 'OUC',
'Overseas British' => 'OVB',
'Overseas Foreign' => 'OVF',
'Scottish Shipping' => 'SCS'

What is your desire?

They would appear as a Special Grouping at the end

**Comment by edickens** [comment] 2019-06-22 22:16
The TNA documents we have are just indexes.  So it is not possible to tell if it is EWS or SCS...
![Capture](https://user-images.githubusercontent.com/8876165/59969360-6d438600-9543-11e9-8e7a-f022563dd614.JPG)
These are deaths on ships.

**Comment by Captainkirkdawson** [comment] 2019-06-22 22:23
I too give up

**Comment by SteveBiggs** [comment] 2019-06-23 08:54
Do we have to use an existing code or can we create a new Chapman code that simply means 'shipping' or 'at sea'?

We don't need a place or church. The ship name would have to go in the Notes.

**Comment by FreecenBren** [comment] 2019-06-23 09:41
As a matter of interest on FreeCEN.
The England & Wales Shipping (EWS) covers the Royal Navy and the Merchants
at sea.They do have the POB as well as the rank and the name of the vessel
etc.

 Some of the records have lists of the Vessels in Foreign Ports and give
the origin of the vessel. Some of these only give the total number of the
crews on board. We still record them though with the vessel name.
So obviously these type of record do not have the POB

I have just searched on FreeCEN One, and used 1871 census and selected the
census county of SCS and they also have the POB

*Piece:* SCT1871/999 *Place:* Merchant Ships -Scottish Shipping *Enumeration
District:* 08
*Civil Parish:* Abertarff Inv *Ecclesiastical Parish, Village or Island:* -
*Folio:* 0 *Page:* 2 *Schedule:* 26
*Address:* (Auguste)

------------------------------
  Surname First name(s) Rel Status Sex Age Occupation Where Born Remarks
    MCRAE   Finlay   Crew   U   M   27   Master    Ross and Cromarty -
Lochalsh
    MCKENZIE   John   Crew   M   M   39   Mate    Ross and Cromarty -
Lochcarron
    MCDONALD   Alex.   Crew   U   M   14   Ordinary Seaman    Ross and
Cromarty - Lochalsh

The reason I used FC1 for the search, is because FC2 at the moment, the SCS
Records are mixed up with the EWS which is what I am currently trying to
sort out.
As you can see though from the copy and paste Scotland SCS, do have the POB
as well.

**Comment by Captainkirkdawson** [comment] 2019-06-23 20:42
The British Standards produced a standard for county codes taking over from the FFHS which produced the original Chapman Codes. I do not have access to the publications nor am I going to buy a copy. BS 6879

More recently there has been international standardization in ISO 3166-2

These have extended the number of codes. Where FreeCEN obtained the specials noted earlier is unknown.

I presume since we will only use the code internally we can use our own together with a plain language interpretation.

Perhaps  Shipboard  SEA or what ever as well as something else for born married or died in some other country

Policy direction needed.

**Comment by edickens** [comment] 2019-06-24 07:53
SEA would be ideal.
What about OVS for Overseas, to cover any entries outside the UK and Ireland.  It doesn't seem to have been used http://home.vicnet.net.au/~mgfhs/chworld.htm

**Comment by PatReynolds** [comment] 2019-06-30 17:40
I'm happy with SEA.  I think for searching purposes, OVS is fine.  Text 'At Sea' and 'Overseas'?  With drop-down of country names as recorded in the document?  I don't think we can use a current non-time-enabled standard for country names as we would need to update historic records to use it (possibly in ways offensive to some people).  Using the city name used by the British at the time the record was created might be the policy to go with for consular registrations.  Perhaps the base or military unit for military records (as dictated by the original document).

**Comment by edickens** [comment] 2019-06-30 18:16
I think that SEA should have just one Place "At sea".  Any place information in the entry can go in "Abode" and will be found in the search results.  We don't want to create thousands of places under SEA with only a very few entries in each.

**Comment by edickens** [comment] 2019-06-30 18:17
Can SEA be create ASAP?  I have many gigabytes of images on my PC to upload.

**Comment by Sherlock21** [comment] 2019-06-30 18:24
I agree with EricD in his post 2 items above here - and with both his points.

**Comment by SteveBiggs** [comment] 2019-06-30 20:39
Who can create new counties (SEA)?

**Comment by Captainkirkdawson** [comment] 2019-06-30 21:00
Do I conclude from this that we need SEA and OVS neither is used in CEN. I do not know about BMD.  The text which is the MOST important is to be "At Sea" and 'Overseas" ? Creating them is easily done. Using them may be a very different kettle of fish.  There can be NO drop down is possible for a Chapman Code. A place can possibly linked to  either.  BUT we need to define those if they are to appear. Cannot code perhaps; we need clear decision to define them or not and if so what they are.

**Comment by edickens** [comment] 2019-07-01 07:48
I hope that SEA and OVS can be treated just like any other County.  That means that they will have Place, Church, Register Type and Source entries.  They also need to be in the list of Counties to assign a Coordinator.
I am not sure though how the Country will be processed.
Searching should be done in the same way as is done for every other County.

**Comment by edickens** [comment] 2019-07-01 07:50
We appreciate that SEA and OVS are not Chapman Codes in FreeCEN.  But there are no Chapman Codes in FreeCEN which reflect the needs of BMD at sea and overseas entries pre-1837.

**Comment by Sherlock21** [comment] 2019-07-01 16:40
I would agree with SEA for all events which happen in a vessel at sea, and OVS for other events which don't happen at sea but are 'somewhere unspecified, abroad'. However, it would be much more use to 'FreeReg' if the foreign country were to be used if its known.

**Comment by edickens** [comment] 2019-07-02 13:32
Steve and I have had some further thoughts about these records.  They are not Baptisms or Burials.  There are some marriages, but not within a church or parish.  They really should be in FreeBMD.  We also have a lot of work to do which more directly relates to the FreeREG objective.
But these are useful and good quality records.  So I propose to break up the large pdf files into pages of jpg images.  Then upload them directly to the image server.  In this way they will be safe and backed up.  It will also be much easier to move them across for FreeBMD transcribers to work on them.
Does this make sense?  If so we do not need the SEA and OVS chapman codes and this story can be closed.

**Comment by edickens** [comment] 2019-07-03 10:54
Pat is still keen that we put this into FreeREG for now as FreeBMD will not be able to take them for ages.
Steve and I think the best short term solution is to use OVB (Overseas British) as this can cover At Sea and Military and Consular.  It is already set up, so no work needed, except perhaps to make it searchable in the list of Counties, but not until we get doing some transcriptions.  We will use the Place to split them up, then Church if necessary.
We need a Coordinator.  Is there anyone in FreeBMD who would like to come across and do it because these are Births, Marriages and Deaths?

**Comment by SteveBiggs** [comment] 2019-07-03 11:30
Thinking about it, perhaps OUC (Out of Country) would be more appropriate as it's more generic, can cover At Sea or anywhere away from the UK and does not specify whether British or Foreign.

We could poll the FreeREG coordinators to see if there is one who has no data for their county would like to take this up? They should already have some transcribers to assign to.

**Comment by edickens** [comment] 2019-07-03 12:30
Wouldn't OUC, as we have already suggested, be much the same as OVS?

**Comment by SteveBiggs** [comment] 2019-07-03 13:30
It would be anywhere out of the UK, including At Sea, on Military assignment in a foreign country, etc.

OVS does not exist whereas OUC does.

**Comment by edickens** [comment] 2019-07-03 14:04
Understood.  As OUC exists, then use that.

**Comment by richpomfret** [comment] 2019-07-03 16:13
OVB to be used. Description to be confirmed by @edickens and @SteveBiggs

**Comment by AlOneill** [comment] 2019-07-03 23:26
@PatReynolds @richpomfret @edickens @SteveBiggs On reflection, OVB stands for "*Overseas* British" in CEN: if we use it for all, including military *at home*, do we risk it **being needlessly confusing** for a user of both REG and CEN? Or do I miss-understand?

**Comment by AlOneill** [comment] 2019-07-04 00:22
Ah, I forgot that it will  be an internal code only. Apologies.

**Comment by edickens** [comment] 2019-07-04 06:33
We confirm that OVB (Other Records) to be used, in much the same way as FreeCEN.  It to have all the same Actions as any other County.  It to be in England.  The Place to be used to separate the different types and these will show when OVB is selected in a search.  The Abode field to define the actual location.

**Comment by Captainkirkdawson** [comment] 2019-07-04 20:32
Unfortunately we cannot use OVB with a different Description to CEN. The list of codes is common to both apps
Therefore I propose to use OTH "Other Locations"  unless there are concerns with that. The code is not in use elsewhere

**Comment by edickens** [comment] 2019-07-04 21:59
OTH "Other Locations" has my vote.  I didn't suggest it because it is not in the list of FreeREG Chapman codes.

**Comment by Captainkirkdawson** [comment] 2019-07-05 23:34
@edickens @SteveBiggs 
The new Chapman Code OTH Other Locations has been created. You need to now activate that county (New Action) on the County Coordinators Action. Its a new button at the top and that action asks you to assign a county coordinator.
Once you have done that you can manage that county as you would any other. You can add places etc, churches and registers as well as manage images. The one flag is that we still demand a Grid Reference or Lat/lon for the place; suggest something off the coast!!!
It is running for basic checkout on test2

**Comment by SteveBiggs** [comment] 2019-07-06 11:18
I assume that Eric has activated the county as it has him as CC. I created a place called 'At Sea' with a church called 'At Sea' and uploaded a test file with one entry with a register type of 'Unknown'.

The place Lat/Lon had to be between 45 & 70 and -10 & 5 respectively so I set it to 46.0, -9.0 putting it somewhere in the Bay of Biscay.

All seems to work as expected.

**Comment by edickens** [comment] 2019-07-06 13:25
Yes, I activated and put myself as CC.
I tried to create a place and thought I had.  But perhaps the Lat/Lon was wrong.  I don't remember seeing an error report.
So this all looks OK.  Go to production and I can start uploading my 10GB of images!!!
I see that it is searchable as well..
![Capture](https://user-images.githubusercontent.com/8876165/60756790-dc1be700-9ff9-11e9-8045-17b10e312943.JPG)

**Comment by Captainkirkdawson** [comment] 2019-07-06 16:41
I have disabled the county description in the edit. Have added a disabled display of the chapman code in the edit.
Other Locations was used for description as counties are locations. You can add explanatory notes to the Other Locations if you wish.
@edickens I do not understand your issue of inability to create a place, church or register. Unable to duplicate any issue and @SteveBiggs clearly has done so. It is urgent that you document the issue before we put into production.

**Comment by edickens** [comment] 2019-07-06 17:53
As said.  I must have got something wrong when tying to created a Place. As Steve says, works fine.

**Comment by Sherlock21** [comment] 2019-07-06 19:35
But events which are all to be 'Somewhere at Sea', that seems illogical and wrong to me giving them a fictitious location ref just because tie program needs one

Are you going to have a Placename and church for every vessel at sea? or what?
and mix up vessels at sea, with for example Embassies abroad?

**Comment by Sherlock21** [comment] 2019-07-06 19:35
But events which are all to be 'Somewhere at Sea', that seems illogical and wrong to me giving them a fictitious location ref just because tie program needs one

Are you going to have a Placename and church for every vessel at sea? or what?
and mix up vessels at sea, with for example Embassies abroad?

**Comment by Sherlock21** [comment] 2019-07-06 19:35
But events which are all to be 'Somewhere at Sea', that seems illogical and wrong to me giving them a fictitious location ref just because tie program needs one

Are you going to have a Placename and church for every vessel at sea? or what?
and mix up vessels at sea, with for example Embassies abroad?

**Comment by Sherlock21** [comment] 2019-07-06 19:38
\\PS I started writing the above in response to Steve's experience now 5 items above - but its still relevant I think.

**Comment by Sherlock21** [comment] 2019-07-06 19:38
\\PS I started writing the above in response to Steve's experience now 5 items above - but its still relevant I think.

**Comment by edickens** [comment] 2019-07-06 20:46
No, we are thinking of adding Ship name, or overseas place in the Abode.  There will only be few entries for each ship.  So Place and Church will most likely be the same such as "At sea".  Military might be different as the records are by Regiment.
But, although I have a lot of records, this is not the main part of FreeREG.

**Comment by SteveBiggs** [comment] 2019-07-07 12:14
The Lat/Lons have been set up assuming everything is in the UK, so whatever we set it to for events outside the UK will be wrong and therefore irrelevant. We plan to have a single Place - 'At Sea' to cover all events on board ships. As Eric says, there will be very few events on any given ship so setting a separate place/church for each would be too cumbersome.

Other events abroad such as at Embassies or on Military service, etc. will have different Places as appropriate.

**Comment by Captainkirkdawson** [comment] 2019-07-07 16:48
@edickens @SteveBiggs Deployed to production. You will need to activate there and create At Sea there

**Closed by Captainkirkdawson** 2019-07-07 16:48 UTC
Labels: Image, P18, needs info
