### ISSUE TITLE
DAP -  review image of event if permitted

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#948] opened 2016-09-22 09:02 UTC

**Comment by edickens** [comment] 2016-09-22 09:17
I think we should investigate if we can show researchers the images for 
checking purposes.  I would suggest that only those researchers (and 
others) who have registered and agreed to our T&C, which should include 
using the images for checking purposes, should have this facility.  It 
gives us an audit trail of who has looked at what.  E

**Comment by PatReynolds** [comment] 2016-09-26 08:16
The getting of permissions is a separate story, but agree for this story: functionality should include allowing RegisteredResearchers to view, and could include audit trail of who has viewed the image.

**Comment by Sherlock21** [comment] 2016-09-26 08:25
In my view, the DPA says: publish personal info only on a meed to know basis - and letting registered researchers see private emails addresses when the owner of that email address did not give their explicit agreement seems the wrong side of correct.

Eric B

**Comment by richpomfret** [comment] 2017-08-07 16:26
Finetuning.

**Comment by Captainkirkdawson** [comment] 2018-02-25 05:10
duplicate of #1279

**Closed by Captainkirkdawson** 2018-02-25 05:10 UTC
Labels: Actor: researcher, DAP, Image, ready
